"""Canonical grocery staples for Safeway search seeding (~50 items)."""

CANONICAL_ITEMS: tuple[str, ...] = (
    "whole milk",
    "large eggs",
    "unsalted butter",
    "whole wheat bread",
    "boneless chicken breast",
    "ground beef",
    "bacon",
    "atlantic salmon fillet",
    "greek yogurt",
    "cheddar cheese",
    "bananas",
    "gala apples",
    "navel oranges",
    "strawberries",
    "blueberries",
    "hass avocados",
    "roma tomatoes",
    "yellow onions",
    "russet potatoes",
    "baby carrots",
    "broccoli crowns",
    "baby spinach",
    "romaine lettuce",
    "bell peppers",
    "garlic",
    "white rice",
    "spaghetti pasta",
    "rolled oats",
    "cheerios cereal",
    "all purpose flour",
    "granulated sugar",
    "extra virgin olive oil",
    "vegetable oil",
    "creamy peanut butter",
    "strawberry jam",
    "ground coffee",
    "black tea bags",
    "orange juice",
    "cola soda",
    "bottled water",
    "paper towels",
    "toilet paper",
    "dish soap",
    "laundry detergent",
    "shampoo",
    "toothpaste",
    "disposable diapers",
    "baby food pouches",
    "dry dog food",
    "dry cat food",
)
