#!/usr/bin/env python3
"""Generate src/data/canonicalTrackerFamilies.generated.ts from YAML source of truth."""

from __future__ import annotations

import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from price_tracker.canonical_families import (  # noqa: E402
    HOMEPAGE_SECTION_LABELS,
    HOMEPAGE_SECTION_ORDER,
    LEGACY_CANONICAL_TO_FAMILY,
    load_families,
    validate_families,
)

ROOT = SCRIPT_DIR.parent
OUTPUT = ROOT / "src" / "data" / "canonicalTrackerFamilies.generated.ts"
POPULAR_YAML = ROOT / "data" / "popular_this_week.yaml"


def _normalize_popular_entries(entries: list | None) -> list[dict]:
    normalized: list[dict] = []
    for entry in entries or []:
        normalized.append(
            {
                "title": entry.get("title", ""),
                "trackerFamilyIds": entry.get("tracker_family_ids")
                or entry.get("trackerFamilyIds")
                or [],
                "reason": entry.get("reason", ""),
                "displayOrder": entry.get("display_order")
                or entry.get("displayOrder")
                or 0,
            }
        )
    return normalized


def load_popular_yaml() -> dict:
    import yaml

    if not POPULAR_YAML.is_file():
        return {"week": "", "stores": {"safeway": [], "vons": []}}
    with POPULAR_YAML.open(encoding="utf-8") as handle:
        raw = yaml.safe_load(handle) or {}
    stores = raw.get("stores") or {}
    return {
        "week": raw.get("week") or "",
        "stores": {
            "safeway": _normalize_popular_entries(stores.get("safeway")),
            "vons": _normalize_popular_entries(stores.get("vons")),
        },
    }


def render_ts() -> str:
    families = load_families()
    errors = validate_families(families)
    if errors:
        raise SystemExit("YAML validation failed:\n" + "\n".join(errors))

    family_payload = [
        {
            "id": f.id,
            "displayName": f.canonical_tracker_family,
            "subtitle": f.size_format_subtitle,
            "displayOrder": f.display_order,
            "homepageSection": f.homepage_section,
            "category": f.category,
            "confidence": f.confidence,
            "costcoComparable": True,
            "searchAliases": list(f.include) + [f.canonical_tracker_family],
            "legacyCanonicalIds": [
                legacy
                for legacy, target in LEGACY_CANONICAL_TO_FAMILY.items()
                if target == f.id
            ],
        }
        for f in families
    ]

    sections = [
        {
            "id": section_id,
            "label": HOMEPAGE_SECTION_LABELS[section_id],
            "order": index + 1,
        }
        for index, section_id in enumerate(HOMEPAGE_SECTION_ORDER)
    ]

    popular = load_popular_yaml()
    section_union = "\n".join(f'  | "{s}"' for s in HOMEPAGE_SECTION_ORDER)

    return f"""// AUTO-GENERATED by scripts/generate_canonical_families.py — do not edit by hand.
// Source: data/canonical_tracker_families.yaml

export type HomepageSectionId =
{section_union};

export type CanonicalTrackerFamily = {{
  id: string;
  displayName: string;
  subtitle: string;
  displayOrder: number;
  homepageSection: HomepageSectionId;
  category: string;
  confidence: "high" | "medium" | "low" | "working";
  costcoComparable: boolean;
  searchAliases: string[];
  /** Old canonical_products ids whose historical rows map to this family. */
  legacyCanonicalIds: string[];
}};

export type HomepageSection = {{
  id: HomepageSectionId;
  label: string;
  order: number;
}};

export type PopularThisWeekEntry = {{
  title: string;
  trackerFamilyIds: string[];
  reason: string;
  displayOrder: number;
}};

export type PopularThisWeekStore = "safeway" | "vons";

export const HOMEPAGE_SECTIONS: HomepageSection[] = {json.dumps(sections, indent=2)};

export const CANONICAL_TRACKER_FAMILIES: CanonicalTrackerFamily[] = {json.dumps(family_payload, indent=2)};

export const LEGACY_CANONICAL_TO_FAMILY: Record<string, string> = {json.dumps(LEGACY_CANONICAL_TO_FAMILY, indent=2)};

export const POPULAR_THIS_WEEK_WEEK: string = {json.dumps(popular.get("week") or "")};

export const POPULAR_THIS_WEEK: Record<PopularThisWeekStore, PopularThisWeekEntry[]> = {{
  safeway: {json.dumps(popular.get("stores", {}).get("safeway", []), indent=2)},
  vons: {json.dumps(popular.get("stores", {}).get("vons", []), indent=2)},
}};
"""


def main() -> None:
    OUTPUT.write_text(render_ts(), encoding="utf-8")
    families = load_families()
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({len(families)} families)")


if __name__ == "__main__":
    main()
