#!/usr/bin/env python3
"""Generate Supabase seed SQL for Vons weekly ad observations."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / "src" / "data" / "vonsWeeklyAdPrices.generated.ts"
BASELINE_TS = ROOT / "src" / "data" / "vonsBaseline.generated.ts"
OUTPUT = ROOT / "supabase" / "migrations" / "20260615_vons_weekly_observations_seed.sql"

VONS_FEED_ID = "vons_albertsons_socal"


def parse_weekly_ts(path: Path) -> tuple[list[dict], dict]:
    text = path.read_text(encoding="utf-8")
    weeks_match = re.search(
        r"export const VONS_WEEKLY_AD_WEEKS.*?=\s*(\[.*?\]);",
        text,
        re.S,
    )
    prices_match = re.search(
        r"export const VONS_WEEKLY_AD_PRICES.*?=\s*(\{.*?\});",
        text,
        re.S,
    )
    if not weeks_match or not prices_match:
        raise RuntimeError(f"Could not parse {path.name}")
    return json.loads(weeks_match.group(1)), json.loads(prices_match.group(1))


def parse_vons_baselines() -> dict[str, float]:
    text = BASELINE_TS.read_text(encoding="utf-8")
    match = re.search(
        r"export const VONS_BASELINE_BY_CANONICAL.*?=\s*(\{.*?\});",
        text,
        re.S,
    )
    if not match:
        return {}
    data = json.loads(match.group(1))
    return {
        cid: float(entry["baselinePrice"])
        for cid, entry in data.items()
        if entry.get("baselinePrice") is not None
    }


def sql_str(value: str | None) -> str:
    if value is None:
        return "null"
    return "'" + value.replace("'", "''") + "'"


def effective(entry: dict | None, baseline: float) -> tuple[float, str, bool]:
    if not entry:
        return baseline, "baseline", True
    ad_price = entry.get("price")
    confidence = entry.get("confidence")
    use_ad = ad_price is not None and confidence is not None and confidence != "low"
    if use_ad:
        return float(ad_price), "weekly_ad", False
    return baseline, "baseline", True


def main() -> None:
    weeks, prices = parse_weekly_ts(GENERATED)
    baselines = parse_vons_baselines()

    if not weeks:
        print(f"No Vons weeks in {GENERATED.name}, skipping seed (run extraction first)")
        return

    if not baselines:
        print(f"No Vons baselines in {BASELINE_TS.name}, using ad prices only where matched")

    lines: list[str] = [
        "-- AUTO-GENERATED by scripts/generate_vons_weekly_observations_seed.py",
        "-- Seeds Vons / Albertsons SoCal weekly ad observations.",
        "",
    ]

    week_index = {w["weekStart"]: w for w in weeks}
    canonical_ids = sorted(set(prices.keys()) | set(baselines.keys()))

    for cid in canonical_ids:
        baseline = baselines.get(cid)
        by_week = prices.get(cid, {})
        for week_start, week in week_index.items():
            entry = by_week.get(week_start)
            if baseline is None and (not entry or entry.get("price") is None):
                continue
            eff, price_type, is_fallback = effective(entry, baseline or 0.0)
            ad_price = entry.get("price") if entry else None
            confidence = entry.get("confidence") if entry else None
            offer = entry.get("offerText") if entry else None
            source_label = f"{week['sourceLabel']} · {week['sourceFile']}"
            lines.append(
                "insert into weekly_price_observations "
                "(canonical_product_id, feed_id, week_start, week_end, ad_price, effective_price, "
                "match_confidence, price_type, is_baseline_fallback, source_label, offer_text) "
                f"values ({sql_str(cid)}, {sql_str(VONS_FEED_ID)}, {sql_str(week_start)}, "
                f"{sql_str(week['weekEnd'])}, "
                f"{ad_price if ad_price is not None else 'null'}, {eff}, "
                f"{sql_str(confidence)}, {sql_str(price_type)}, "
                f"{'true' if is_fallback else 'false'}, {sql_str(source_label)}, {sql_str(offer)}) "
                "on conflict (canonical_product_id, feed_id, week_start) do update set "
                "week_end = excluded.week_end, ad_price = excluded.ad_price, "
                "effective_price = excluded.effective_price, match_confidence = excluded.match_confidence, "
                "price_type = excluded.price_type, is_baseline_fallback = excluded.is_baseline_fallback, "
                "source_label = excluded.source_label, offer_text = excluded.offer_text;"
            )

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({len(weeks)} weeks)")


if __name__ == "__main__":
    main()
