#!/usr/bin/env python3
"""Generate feed_product_matches SQL + frontend fallback TS for Vons baselines."""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

sys.path.insert(0, str(ROOT / "scripts"))
from price_tracker.baseline_per_lb import normalize_baseline_price
CANDIDATES = ROOT / "data" / "processed" / "vons_baseline_candidates_v1.csv"
NEW_ONLY_CANDIDATES = ROOT / "data" / "processed" / "vons_baseline_candidates_new_only.csv"
SQL_OUTPUT = ROOT / "supabase" / "migrations" / "20260612_vons_feed_matches_seed.sql"
TS_OUTPUT = ROOT / "src" / "data" / "vonsBaseline.generated.ts"

FEED_ID = "vons_albertsons_socal"


def sql_str(value: str | None) -> str:
    if value is None or value == "":
        return "null"
    return "'" + value.replace("'", "''") + "'"


def parse_price(raw: str) -> float | None:
    cleaned = raw.replace("$", "").strip()
    if not cleaned:
        return None
    try:
        return float(cleaned)
    except ValueError:
        return None


def load_best_rows(*paths: Path) -> dict[str, dict[str, str]]:
    best: dict[str, dict[str, str]] = {}
    for path in paths:
        if not path.is_file():
            continue
        with path.open(newline="", encoding="utf-8") as handle:
            for row in csv.DictReader(handle):
                cid = row["canonical_id"]
                rank = int(row.get("candidate_rank") or 99)
                if cid not in best or rank < int(best[cid].get("candidate_rank") or 99):
                    best[cid] = row
    return best


def main() -> None:
    best = load_best_rows(CANDIDATES, NEW_ONLY_CANDIDATES)
    if not best:
        raise FileNotFoundError(
            f"Missing Vons baseline CSV. Run: python scripts/seed_vons_baseline_playwright.py"
        )

    lines = [
        "-- AUTO-GENERATED by scripts/generate_vons_feed_matches.py",
        f"-- Source: {CANDIDATES.relative_to(ROOT)}",
        "",
    ]

    for cid, row in sorted(best.items()):
        raw_price = parse_price(row.get("price", ""))
        if raw_price is None:
            continue
        price, was_normalized = normalize_baseline_price(cid, row.get("product_name", ""), raw_price)
        if was_normalized:
            print(f"  [per-lb] {cid}: ${raw_price} / '{row.get('product_name', '')[:60]}' → ${price}/lb")
        lines.append(
            "insert into feed_product_matches "
            "(canonical_product_id, feed_id, retailer_product_id, upc, "
            "retailer_product_name, size, baseline_price, baseline_source) "
            f"values ({sql_str(cid)}, {sql_str(FEED_ID)}, {sql_str(row.get('pid'))}, "
            f"{sql_str(row.get('upc'))}, {sql_str(row.get('product_name'))}, "
            f"{sql_str(row.get('size'))}, {price}, 'Vons search result CSV (rank 1)') "
            "on conflict (canonical_product_id, feed_id) do update set "
            "retailer_product_id = excluded.retailer_product_id, upc = excluded.upc, "
            "retailer_product_name = excluded.retailer_product_name, size = excluded.size, "
            "baseline_price = excluded.baseline_price, baseline_source = excluded.baseline_source;"
        )

    SQL_OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {SQL_OUTPUT.relative_to(ROOT)} ({len(best)} products)")

    ts_entries: dict[str, dict] = {}
    for cid, row in best.items():
        raw_price = parse_price(row.get("price", ""))
        if raw_price is None:
            continue
        price, _ = normalize_baseline_price(cid, row.get("product_name", ""), raw_price)
        ts_entries[cid] = {
            "baselinePrice": price,
            "baselineSource": "Vons search result CSV (rank 1)",
            "retailerProductId": row.get("pid") or None,
            "upc": row.get("upc") or None,
            "retailerProductName": row.get("product_name") or None,
            "size": row.get("size") or None,
        }

    ts_body = json.dumps(ts_entries, indent=2)
    TS_OUTPUT.write_text(
        f"""// AUTO-GENERATED by scripts/generate_vons_feed_matches.py — do not edit by hand.
// Source: {CANDIDATES.relative_to(ROOT)}

export type VonsBaselineEntry = {{
  baselinePrice: number;
  baselineSource: string;
  retailerProductId: string | null;
  upc: string | null;
  retailerProductName: string | null;
  size: string | null;
}};

export const VONS_BASELINE_BY_CANONICAL: Record<string, VonsBaselineEntry> = {ts_body};
""",
        encoding="utf-8",
    )
    print(f"Wrote {TS_OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
