#!/usr/bin/env python3
"""Generate Supabase seed SQL for price tracker feeds from weeklyAdPrices.generated.ts."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / "src" / "data" / "weeklyAdPrices.generated.ts"
OUTPUT = ROOT / "supabase" / "migrations" / "20260609_price_tracker_seed.sql"

SAFEWAY_FEED_ID = "safeway_bay_area"

BASELINES = {
    "strawberries": (4.99, "Safeway search result CSV", "Strawberries 1 lb"),
    "avocados": (2.0, "Safeway search result CSV", "Medium Hass Avocado"),
    "doritos_nacho_cheese": (5.49, "Safeway search result CSV", "Doritos Nacho Cheese Tortilla Chips"),
    "cheetos_crunchy": (5.49, "Safeway search result CSV", "Cheetos Cheese Flavored Crunchy Snacks"),
    "coke_zero": (12.99, "Safeway search result CSV", "Coca-Cola Zero Sugar Soda"),
    "chobani_greek_yogurt": (7.99, "Safeway search result CSV", "Chobani Non-Fat Plain Greek Yogurt"),
    "cheerios": (6.99, "Safeway search result CSV", "Cheerios Whole Grain Oat Toasted Cereal"),
    "tillamook_ice_cream": (6.99, "Safeway search result CSV", "Tillamook Oregon Strawberry Ice Cream"),
    "mission_tortilla_chips": (4.49, "Safeway search result CSV", "Mission Round Yellow Corn Tortilla Chips"),
    "nature_valley_bars": (4.99, "Safeway search result CSV", "Nature Valley Crunchy Oats 'n Honey Granola Bars"),
}

CANONICAL = [
    ("strawberries", "Strawberries", "strawberries", "1 lb", 1),
    ("avocados", "Hass Avocados", "avocados", "Each", 2),
    ("doritos_nacho_cheese", "Doritos Nacho Cheese", "doritos_nacho_cheese", "9.25 oz", 3),
    ("cheetos_crunchy", "Cheetos Crunchy", "cheetos_crunchy", "8.5 oz", 4),
    ("coke_zero", "Coke Zero", "coke_zero", "12 pack / 12 fl oz", 5),
    ("chobani_greek_yogurt", "Chobani Greek Yogurt", "chobani_greek_yogurt", "32 oz", 6),
    ("cheerios", "Cheerios", "cheerios", "8.9 oz", 7),
    ("tillamook_ice_cream", "Tillamook Ice Cream", "tillamook_ice_cream", "1.75 qt", 8),
    ("mission_tortilla_chips", "Mission Tortilla Chips", "mission_tortilla_chips", "11 oz", 9),
    ("nature_valley_bars", "Nature Valley Bars", "nature_valley_bars", "12 ct", 10),
    ("fage_greek_yogurt", "Fage Greek Yogurt", "fage_greek_yogurt", "32 oz", 11),
    ("frito_lay_multipack_chips", "Frito-Lay Multipack Chips", "frito_lay_multipack_chips", "Multipack", 12),
    ("haagen_dazs_ice_cream", "Häagen-Dazs Ice Cream", "haagen_dazs_ice_cream", "14 oz", 13),
    ("grapes", "Grapes", "grapes", "per lb", 14),
    ("eggs_18_count", "Eggs, 18-count", "eggs_18_count", "18 ct", 15),
    ("oreos_sandwich_cookies", "Oreos / Sandwich Cookies", "oreos_sandwich_cookies", "Family size", 16),
    ("protein_bars", "Protein Bars", "protein_bars", "Varies", 17),
    ("kettle_brand_chips", "Kettle Brand Chips", "kettle_brand_chips", "8 oz", 18),
]


def parse_generated_ts() -> tuple[list[dict], dict]:
    text = GENERATED.read_text(encoding="utf-8")
    weeks_match = re.search(
        r"export const WEEKLY_AD_WEEKS.*?=\s*(\[.*?\]);",
        text,
        re.S,
    )
    prices_match = re.search(
        r"export const WEEKLY_AD_PRICES.*?=\s*(\{.*?\});",
        text,
        re.S,
    )
    if not weeks_match or not prices_match:
        raise RuntimeError("Could not parse weeklyAdPrices.generated.ts")
    weeks = json.loads(weeks_match.group(1))
    prices = json.loads(prices_match.group(1))
    return weeks, prices


def sql_str(value: str | None) -> str:
    if value is None:
        return "null"
    return "'" + value.replace("'", "''") + "'"


def effective(entry: dict | None, baseline: float) -> tuple[float, str, bool]:
    if not entry:
        return baseline, "baseline", True
    ad_price = entry.get("price")
    confidence = entry.get("confidence")
    use_ad = ad_price is not None and confidence is not None and confidence != "low"
    if use_ad:
        return float(ad_price), "weekly_ad", False
    return baseline, "baseline", True


def main() -> None:
    weeks, prices = parse_generated_ts()
    lines: list[str] = [
        "-- AUTO-GENERATED by scripts/generate_price_tracker_seed.py",
        "-- Seeds Safeway Bay Area baseline + weekly observations.",
        "",
    ]

    for cid, name, family, size, order in CANONICAL:
        lines.append(
            "insert into canonical_products (id, display_name, product_family, size_label, sort_order) "
            f"values ({sql_str(cid)}, {sql_str(name)}, {sql_str(family)}, {sql_str(size)}, {order}) "
            "on conflict (id) do update set display_name = excluded.display_name, "
            "product_family = excluded.product_family, size_label = excluded.size_label, "
            "sort_order = excluded.sort_order;"
        )

    lines.append("")
    lines.append(
        "insert into price_feeds (id, label, region_label, store_group, stores, sort_order) values "
        "('safeway_bay_area', 'Safeway', 'Bay Area', 'safeway', array['Safeway'], 1), "
        "('vons_albertsons_socal', 'Vons / Albertsons', 'SoCal', 'vons_albertsons', array['Vons','Albertsons'], 2), "
        "('costco_sf', 'Costco', 'San Francisco', 'costco', array['Costco'], 3), "
        "('costco_oc', 'Costco', 'Orange County', 'costco', array['Costco'], 4) "
        "on conflict (id) do update set label = excluded.label, region_label = excluded.region_label, "
        "store_group = excluded.store_group, stores = excluded.stores, sort_order = excluded.sort_order;"
    )

    lines.append("")
    canonical_sizes = {cid: size for cid, _name, _family, size, _order in CANONICAL}
    for cid in BASELINES:
        baseline, source, retailer_name = BASELINES[cid]
        size = canonical_sizes.get(cid, "")
        lines.append(
            "insert into feed_product_matches "
            "(canonical_product_id, feed_id, retailer_product_name, size, baseline_price, baseline_source) "
            f"values ({sql_str(cid)}, {sql_str(SAFEWAY_FEED_ID)}, {sql_str(retailer_name)}, "
            f"{sql_str(size)}, {baseline}, {sql_str(source)}) "
            "on conflict (canonical_product_id, feed_id) do update set "
            "retailer_product_name = excluded.retailer_product_name, size = excluded.size, "
            "baseline_price = excluded.baseline_price, baseline_source = excluded.baseline_source;"
        )

    lines.append("")
    week_index = {w["weekStart"]: w for w in weeks}
    canonical_ids = sorted(set(BASELINES.keys()) | set(prices.keys()))
    for cid in canonical_ids:
        baseline = BASELINES[cid][0] if cid in BASELINES else None
        by_week = prices.get(cid, {})
        for week_start, week in week_index.items():
            entry = by_week.get(week_start)
            if baseline is None and (not entry or entry.get("price") is None):
                continue
            eff, price_type, is_fallback = effective(entry, baseline or 0.0)
            ad_price = entry.get("price") if entry else None
            confidence = entry.get("confidence") if entry else None
            offer = entry.get("offerText") if entry else None
            source_label = f"{week['sourceLabel']} · {week['sourceFile']}"
            lines.append(
                "insert into weekly_price_observations "
                "(canonical_product_id, feed_id, week_start, week_end, ad_price, effective_price, "
                "match_confidence, price_type, is_baseline_fallback, source_label, offer_text) "
                f"values ({sql_str(cid)}, {sql_str(SAFEWAY_FEED_ID)}, {sql_str(week_start)}, "
                f"{sql_str(week['weekEnd'])}, "
                f"{ad_price if ad_price is not None else 'null'}, {eff}, "
                f"{sql_str(confidence)}, {sql_str(price_type)}, "
                f"{'true' if is_fallback else 'false'}, {sql_str(source_label)}, {sql_str(offer)}) "
                "on conflict (canonical_product_id, feed_id, week_start) do update set "
                "week_end = excluded.week_end, ad_price = excluded.ad_price, "
                "effective_price = excluded.effective_price, match_confidence = excluded.match_confidence, "
                "price_type = excluded.price_type, is_baseline_fallback = excluded.is_baseline_fallback, "
                "source_label = excluded.source_label, offer_text = excluded.offer_text;"
            )

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
