// AUTO-GENERATED by scripts/generate_canonical_families.py; do not edit by hand.
// Source: data/canonical_tracker_families.yaml

export type HomepageSectionId =
  | "stock_up_snacks_and_treats"
  | "fresh_produce"
  | "dairy_breakfast_bakery"
  | "meat_and_seafood"
  | "drinks";

export type CanonicalTrackerFamily = {
  id: string;
  displayName: string;
  subtitle: string;
  displayOrder: number;
  homepageSection: HomepageSectionId;
  category: string;
  confidence: "high" | "medium" | "low" | "working";
  costcoComparable: boolean;
  searchAliases: string[];
  /** Old canonical_products ids whose historical rows map to this family. */
  legacyCanonicalIds: string[];
  /** Families sharing this id collapse to one card; UI picks the better deal. */
  displayCardGroup: string;
};

export type HomepageSection = {
  id: HomepageSectionId;
  label: string;
  order: number;
};

export type PopularThisWeekEntry = {
  title: string;
  trackerFamilyIds: string[];
  reason: string;
  /** Optional editorial subtitle override (curated shortlist cards). */
  subtitle: string;
  /** Optional editorial badge label override (e.g. FRIDAY, DEAL, MEAT). */
  badge: string;
  /** Curated editorial display price (effective_price or ad_price); empty for YAML/Vons cards. */
  price: string;
  /** Curated availability label, e.g. "Friday-only" or "Full week"; empty for YAML/Vons cards. */
  availability: string;
  /** True when the deal is a Friday-only editorial highlight. */
  fridayOnly: boolean;
  displayOrder: number;
};

export type PopularThisWeekStore = "safeway" | "vons";

export const HOMEPAGE_SECTIONS: HomepageSection[] = [
  {
    "id": "stock_up_snacks_and_treats",
    "label": "Snacks and Treats",
    "order": 1
  },
  {
    "id": "fresh_produce",
    "label": "Fresh produce",
    "order": 2
  },
  {
    "id": "dairy_breakfast_bakery",
    "label": "Dairy, breakfast & bakery",
    "order": 3
  },
  {
    "id": "meat_and_seafood",
    "label": "Meat & seafood",
    "order": 4
  },
  {
    "id": "drinks",
    "label": "Drinks",
    "order": 5
  }
];

export const CANONICAL_TRACKER_FAMILIES: CanonicalTrackerFamily[] = [
  {
    "id": "doritos_5_13oz",
    "displayName": "Doritos",
    "subtitle": "regular size, 5\u201313 oz",
    "displayOrder": 1,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Doritos Nacho Cheese",
      "Doritos Cool Ranch",
      "Doritos Spicy Nacho",
      "Doritos Flamin Hot",
      "Doritos Dinamita",
      "Doritos limited edition flavors",
      "regular Doritos bags in size range",
      "Doritos"
    ],
    "legacyCanonicalIds": [
      "doritos_nacho_cheese"
    ],
    "displayCardGroup": ""
  },
  {
    "id": "cheetos_regular_bags",
    "displayName": "Cheetos",
    "subtitle": "regular size, 6.5\u201310 oz",
    "displayOrder": 2,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Cheetos Crunchy",
      "Cheetos Puffs",
      "Cheetos Popcorn",
      "Cheetos Flamin Hot",
      "Cheetos Extra Flamin Hot",
      "Cheetos Crunchy Flamin Hot Dill Pickle",
      "Cheetos Cheddar Jalape\u00f1o",
      "regular Cheetos bags in size range",
      "Cheetos"
    ],
    "legacyCanonicalIds": [
      "cheetos_crunchy"
    ],
    "displayCardGroup": ""
  },
  {
    "id": "cheetos_party_size",
    "displayName": "Cheetos Party Size",
    "subtitle": "family size, 15 oz",
    "displayOrder": 3,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Cheetos Party Size",
      "Cheetos Party Size"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "lays_potato_chips_regular",
    "displayName": "Lay's potato chips",
    "subtitle": "regular bags 5\u201313 oz, including Poppables",
    "displayOrder": 4,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Lay's Classic",
      "Lay's Barbecue",
      "Lay's Sour Cream & Onion",
      "Lay's Lim\u00f3n",
      "Lay's Salt & Vinegar",
      "Lay's Dill Pickle",
      "Lay's Cheddar & Sour Cream",
      "Lay's Poppables",
      "Poppables",
      "Lay's Popables",
      "Lay's potato chips"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "lays_kettle_cooked",
    "displayName": "Lay's Kettle Cooked chips",
    "subtitle": "regular kettle bags 6\u20138 oz",
    "displayOrder": 5,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Lay's Kettle Cooked Original",
      "Lay's Kettle Cooked Jalape\u00f1o",
      "Lay's Kettle Cooked BBQ",
      "Lay's Kettle Cooked Sea Salt & Vinegar",
      "Lay's Kettle Cooked Cajun Spiced",
      "Lay's Kettle Cooked",
      "Lay's Kettle",
      "Kettle Cooked Potato Chips",
      "Kettle Cooked Chips",
      "Lay's Kettle Cooked chips"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "lays_party_size",
    "displayName": "Lay's Party Size",
    "subtitle": "family size, 12.5\u201313 oz",
    "displayOrder": 6,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Lay's Party Size",
      "Lay's Party Size"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "kettle_brand_chips",
    "displayName": "Kettle Brand potato chips",
    "subtitle": "regular size, 6.5\u20138.5 oz",
    "displayOrder": 7,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Kettle Brand Sea Salt",
      "Kettle Brand Jalape\u00f1o",
      "Kettle Brand Backyard Barbeque",
      "Kettle Brand Salt & Vinegar",
      "Kettle Brand Honey Dijon",
      "Kettle Brand Chips",
      "Kettle Brand potato chips",
      "Kettle Potato Chips",
      "Kettle chips",
      "Kettle Brand potato chips"
    ],
    "legacyCanonicalIds": [
      "kettle_brand_chips"
    ],
    "displayCardGroup": ""
  },
  {
    "id": "ruffles_regular_bags",
    "displayName": "Ruffles",
    "subtitle": "regular size, 5\u201313 oz",
    "displayOrder": 8,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Ruffles Original",
      "Ruffles Cheddar & Sour Cream",
      "Ruffles Sour Cream & Onion",
      "Ruffles Flamin' Hot",
      "Ruffles potato chips",
      "Ruffles"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "sun_chips_7oz",
    "displayName": "Sun Chips",
    "subtitle": "regular size, 7 oz",
    "displayOrder": 9,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Sun Chips Original",
      "Sun Chips Harvest Cheddar",
      "Sun Chips Garden Salsa",
      "Sun Chips French Onion",
      "Sun Chips 7 oz bags",
      "SunChips",
      "Sun Chips"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "tostitos_tortilla_chips",
    "displayName": "Tostitos tortilla chips",
    "subtitle": "regular size, 9\u201313 oz",
    "displayOrder": 10,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Tostitos Scoops",
      "Tostitos Restaurant Style",
      "Tostitos Cantina",
      "Tostitos tortilla chips",
      "Tostitos tortilla chips"
    ],
    "legacyCanonicalIds": [
      "mission_tortilla_chips"
    ],
    "displayCardGroup": ""
  },
  {
    "id": "simply_snacks",
    "displayName": "Simply snacks",
    "subtitle": "regular size, 4.5\u201313 oz",
    "displayOrder": 11,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Simply Cheetos",
      "Simply Cheetos Puffs",
      "Simply Doritos",
      "Simply Lay's",
      "Simply Ruffles",
      "Simply Popables",
      "Simply NKD",
      "Simply snacks",
      "Simply snacks"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "simply_party_size",
    "displayName": "Simply Party Size",
    "subtitle": "family size, 10\u201311 oz",
    "displayOrder": 12,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Simply Party Size",
      "Simply large bags",
      "Simply Party Size"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "popcorners",
    "displayName": "PopCorners",
    "subtitle": "regular size, 5\u201310.75 oz",
    "displayOrder": 13,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "PopCorners",
      "Popcorners",
      "Pop Corners",
      "PopCorners"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "ritz_crackers",
    "displayName": "Ritz crackers",
    "subtitle": "regular size, 8.8\u201313.7 oz",
    "displayOrder": 13,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "cookies_crackers",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Ritz Original",
      "Ritz Fresh Stacks",
      "Ritz Crisp & Thins",
      "Ritz Bits",
      "Ritz Drizzled Minis",
      "Ritz crackers"
    ],
    "legacyCanonicalIds": [
      "ritz_crackers_snacks"
    ],
    "displayCardGroup": ""
  },
  {
    "id": "ritz_toasted_chips",
    "displayName": "Nabisco Ritz Toasted Chips",
    "subtitle": "regular size, 7\u20138.1 oz",
    "displayOrder": 14,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "cookies_crackers",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Ritz Toasted Chips",
      "Nabisco Ritz Toasted Chips"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "nabisco_snack_crackers_regular",
    "displayName": "Wheat Thins, Triscuit & Chicken in a Biskit \u2014 regular size",
    "subtitle": "regular size, 3.5\u20139.1 oz",
    "displayOrder": 15,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "cookies_crackers",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Nabisco Snack Crackers",
      "Nabisco snack crackers",
      "Wheat Thins",
      "Triscuit",
      "Triscuit Crackers",
      "Chicken in a Biskit",
      "Chicken in a Biscuit",
      "Chicken and a Biskit",
      "Chicken and a Biscuit",
      "Wheat Thins, Triscuit & Chicken in a Biskit \u2014 regular size"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "nabisco_snack_crackers",
    "displayName": "Wheat Thins, Triscuit & Chicken in a Biskit",
    "subtitle": "family size, 11.5\u201314 oz",
    "displayOrder": 16,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "cookies_crackers",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Wheat Thins",
      "Wheat Thins Family Size",
      "Triscuit",
      "Triscuit Family Size",
      "Chicken in a Biskit",
      "Chicken in a Biskit Family Size",
      "Nabisco Snack Crackers Family Size",
      "Nabisco snack crackers",
      "Wheat Thins, Triscuit & Chicken in a Biskit"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "cheez_it_crackers",
    "displayName": "Cheez-It crackers",
    "subtitle": "regular size, 6.5\u201312.4 oz",
    "displayOrder": 16,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "cookies_crackers",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Cheez-It Original",
      "Cheez-It White Cheddar",
      "Cheez-It Extra Toasty",
      "Cheez-It Snap'd",
      "Cheez-It Puff'd",
      "Cheez-It Ultimate Snack Mix",
      "Cheez-It Snack Mix",
      "Cheez-It crackers"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "chips_ahoy",
    "displayName": "Chips Ahoy cookies",
    "subtitle": "regular size, 9.5\u201313 oz",
    "displayOrder": 17,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "cookies_crackers",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Chips Ahoy Original",
      "Chips Ahoy Chewy",
      "Chips Ahoy Chunky",
      "Chips Ahoy Mini",
      "Chips Ahoy limited edition flavors",
      "Chips Ahoy cookies"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "oreo_family_size",
    "displayName": "Oreo cookies",
    "subtitle": "family size, 10.68\u201318.71 oz",
    "displayOrder": 18,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "cookies_crackers",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Oreo Original",
      "Oreo Double Stuf",
      "Oreo Golden",
      "Oreo Thins",
      "Oreo limited edition flavors",
      "family size Oreo",
      "Oreo Family Size",
      "family size Oreos",
      "Oreo cookies"
    ],
    "legacyCanonicalIds": [
      "oreos_sandwich_cookies"
    ],
    "displayCardGroup": ""
  },
  {
    "id": "goldfish_bags",
    "displayName": "Goldfish",
    "subtitle": "regular size, 6\u20138 oz",
    "displayOrder": 19,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "crackers_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Goldfish crackers",
      "Goldfish crisps",
      "Goldfish flavor blasted",
      "Goldfish bags in size range",
      "Goldfish"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "keebler_sandwich_crackers",
    "displayName": "Keebler sandwich crackers",
    "subtitle": "8-pack boxes",
    "displayOrder": 20,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "cookies_crackers",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Keebler sandwich crackers",
      "Keebler cheese crackers",
      "Keebler peanut butter crackers",
      "Keebler sandwich crackers"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "coca_cola_12packs",
    "displayName": "Coca-Cola",
    "subtitle": "12-pack, 12 fl oz cans",
    "displayOrder": 21,
    "homepageSection": "drinks",
    "category": "beverages",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Coca-Cola 12-pack",
      "Coke 12-pack",
      "Coke Zero 12-pack",
      "Diet Coke 12-pack",
      "Sprite only if ad groups under Coca-Cola family and user approves",
      "Coca-Cola"
    ],
    "legacyCanonicalIds": [
      "coke_zero"
    ],
    "displayCardGroup": ""
  },
  {
    "id": "pepsi_12packs",
    "displayName": "Pepsi",
    "subtitle": "12-pack, 12 fl oz cans",
    "displayOrder": 22,
    "homepageSection": "drinks",
    "category": "beverages",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Pepsi 12-pack",
      "Diet Pepsi 12-pack",
      "Pepsi Zero 12-pack",
      "Pepsi"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "dr_pepper_12packs",
    "displayName": "Dr Pepper",
    "subtitle": "12-pack, 12 fl oz cans",
    "displayOrder": 23,
    "homepageSection": "drinks",
    "category": "beverages",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Dr Pepper 12-pack",
      "Diet Dr Pepper 12-pack",
      "Dr Pepper Zero Sugar 12-pack",
      "Dr Pepper"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "lacroix_8pack",
    "displayName": "LaCroix sparkling water",
    "subtitle": "8-pack, 12 fl oz cans",
    "displayOrder": 24,
    "homepageSection": "drinks",
    "category": "beverages",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "LaCroix",
      "La Croix",
      "LaCroix sparkling water",
      "LaCroix 8-pack",
      "LaCroix sparkling water"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "simply_refrigerated_juice_lemonade",
    "displayName": "Simply juice",
    "subtitle": "46\u201352 fl oz bottles",
    "displayOrder": 25,
    "homepageSection": "drinks",
    "category": "beverages",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Simply Lemonade",
      "Simply Juice Drink",
      "Simply Orange",
      "Simply Light Orange",
      "Simply Limeade",
      "Simply juice"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "haagen_dazs_pints",
    "displayName": "H\u00e4agen-Dazs ice cream pints",
    "subtitle": "14 oz pints",
    "displayOrder": 26,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "ice_cream",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "H\u00e4agen-Dazs pint",
      "Haagen Dazs pint",
      "H\u00e4agen-Dazs 14 oz",
      "H\u00e4agen-Dazs ice cream",
      "Haagen Dazs ice cream",
      "H\u00e4agen-Dazs ice cream pints"
    ],
    "legacyCanonicalIds": [
      "haagen_dazs_ice_cream"
    ],
    "displayCardGroup": ""
  },
  {
    "id": "ben_jerrys_ice_cream",
    "displayName": "Ben & Jerry's ice cream",
    "subtitle": "pints, non-dairy pints, or 4 ct bars",
    "displayOrder": 27,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "ice_cream",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Ben & Jerry's pint",
      "Ben and Jerry's",
      "B&J",
      "non-dairy pints",
      "Ben & Jerry's bars",
      "Ben & Jerry's ice cream"
    ],
    "legacyCanonicalIds": [
      "ben_jerrys_ice_cream"
    ],
    "displayCardGroup": ""
  },
  {
    "id": "dreyers_tubs",
    "displayName": "Dreyer's ice cream",
    "subtitle": "1.5 qt tubs",
    "displayOrder": 28,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "ice_cream",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Dreyer's ice cream",
      "Dreyers ice cream",
      "Dreyer's 1.5 qt",
      "Dreyer's ice cream"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "breyers_ice_cream",
    "displayName": "Breyers ice cream",
    "subtitle": "tubs, including Carb Smart and Sunday Swirls",
    "displayOrder": 29,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "ice_cream",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Breyers",
      "Breyers Carb Smart",
      "Breyers Sunday Swirls",
      "Breyers Natural Vanilla",
      "Breyers Sundae Swirls",
      "Breyers CarbSmart",
      "Breyers ice cream"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "tillamook_ice_cream",
    "displayName": "Tillamook ice cream",
    "subtitle": "1.5 qt tubs or 4 ct bars when grouped",
    "displayOrder": 30,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "ice_cream",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Tillamook ice cream",
      "Tillamook 1.5 qt",
      "Tillamook bars",
      "Tillamook ice cream"
    ],
    "legacyCanonicalIds": [
      "tillamook_ice_cream"
    ],
    "displayCardGroup": ""
  },
  {
    "id": "haagen_dazs_bars_novelties",
    "displayName": "H\u00e4agen-Dazs bars / novelties",
    "subtitle": "3\u20134 ct boxes",
    "displayOrder": 31,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "ice_cream",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "H\u00e4agen-Dazs bars",
      "H\u00e4agen-Dazs cones",
      "Haagen Dazs novelties",
      "H\u00e4agen-Dazs bars / novelties"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "dreyers_novelties",
    "displayName": "Dreyer's novelties",
    "subtitle": "4 ct boxes",
    "displayOrder": 32,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "ice_cream",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Dreyer's bars",
      "Dreyer's cones",
      "Dreyer's novelties 4 ct",
      "Dreyer's novelties"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "strawberries_1_2lb",
    "displayName": "Strawberries",
    "subtitle": "1 lb or 2 lb packs; normalize per lb",
    "displayOrder": 33,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "conventional strawberries 1 lb",
      "conventional strawberries 2 lb",
      "fresh strawberries",
      "strawberry clamshells",
      "Strawberries"
    ],
    "legacyCanonicalIds": [
      "strawberries"
    ],
    "displayCardGroup": ""
  },
  {
    "id": "seedless_grapes_per_lb",
    "displayName": "Seedless grapes",
    "subtitle": "per lb; normalize bags to per lb",
    "displayOrder": 34,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "red seedless grapes",
      "green seedless grapes",
      "seedless grapes per lb",
      "3 lb seedless grape bags when advertised",
      "Seedless grapes"
    ],
    "legacyCanonicalIds": [
      "grapes"
    ],
    "displayCardGroup": ""
  },
  {
    "id": "cherries_per_lb",
    "displayName": "Cherries",
    "subtitle": "per lb",
    "displayOrder": 35,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "red cherries",
      "cherries per lb",
      "fresh cherries",
      "Cherries"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "berries_6oz",
    "displayName": "Blueberries / raspberries / blackberries",
    "subtitle": "6 oz clamshells",
    "displayOrder": 36,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "blueberries",
      "raspberries",
      "blackberries",
      "blueberries 6 oz",
      "raspberries 6 oz",
      "blackberries 6 oz",
      "berries 6 oz",
      "Blueberries / raspberries / blackberries"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "hass_avocados_each",
    "displayName": "Hass avocados",
    "subtitle": "each or multi-buy",
    "displayOrder": 37,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Hass avocado",
      "Hass avocados",
      "avocado each",
      "avocados 4 for",
      "Hass avocados"
    ],
    "legacyCanonicalIds": [
      "avocados"
    ],
    "displayCardGroup": ""
  },
  {
    "id": "mangoes_each",
    "displayName": "Mangoes",
    "subtitle": "each or multi-buy",
    "displayOrder": 38,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "mango",
      "mangoes",
      "large mangoes",
      "mango each",
      "Mangoes"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "peaches_per_lb",
    "displayName": "Peaches",
    "subtitle": "per lb",
    "displayOrder": 39,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "yellow peaches",
      "white peaches",
      "fresh peaches",
      "peaches per lb",
      "Peaches"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "nectarines_per_lb",
    "displayName": "Nectarines",
    "subtitle": "per lb",
    "displayOrder": 40,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "yellow nectarines",
      "white nectarines",
      "fresh nectarines",
      "nectarines per lb",
      "Nectarines"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "plums_per_lb",
    "displayName": "Plums",
    "subtitle": "per lb",
    "displayOrder": 41,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "red plums",
      "black plums",
      "fresh plums",
      "plums per lb",
      "Plums"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "sweet_corn",
    "displayName": "Sweet corn",
    "subtitle": "each or multi-buy",
    "displayOrder": 42,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "sweet corn",
      "corn on the cob",
      "corn 8 for",
      "corn 3 for",
      "Sweet corn"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "eggs_dozen_normalized",
    "displayName": "Lucerne Eggs",
    "subtitle": "Lucerne large eggs, 12-count",
    "displayOrder": 43,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "dairy",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Lucerne eggs",
      "Lucerne Large Eggs",
      "Lucerne Cage Free Eggs",
      "Lucerne Farms Eggs",
      "Lucerne eggs"
    ],
    "legacyCanonicalIds": [
      "eggs_18_count"
    ],
    "displayCardGroup": "lucerne_eggs"
  },
  {
    "id": "lucerne_eggs_18",
    "displayName": "Lucerne Eggs (18-count)",
    "subtitle": "Lucerne large eggs, 18-count",
    "displayOrder": 43,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "dairy",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Lucerne eggs",
      "Lucerne Large Eggs",
      "Lucerne Cage Free Eggs",
      "Lucerne Farms Eggs",
      "Lucerne eggs 18-count"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": "lucerne_eggs"
  },
  {
    "id": "butter_16oz",
    "displayName": "Butter",
    "subtitle": "16 oz sticks / quarters; normalize to 16 oz",
    "displayOrder": 44,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "dairy",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Lucerne butter 16 oz",
      "Challenge butter 16 oz",
      "Challenge Butter",
      "Danish Creamery butter 16 oz",
      "Danish Creamery Butter",
      "Land O Lakes butter 16 oz",
      "Kerrygold butter when comparable size or normalized",
      "store-brand butter 16 oz",
      "name-brand butter 16 oz",
      "butter 16 oz sticks",
      "butter sticks 16 oz",
      "Butter"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "sliced_or_shredded_cheese_6_8oz",
    "displayName": "Sliced or shredded cheese",
    "subtitle": "6\u20138 oz packages",
    "displayOrder": 45,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "dairy",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Lucerne shredded cheese 6\u20138 oz",
      "Lucerne sliced cheese 6\u20138 oz",
      "Sargento shredded cheese 6\u20138 oz",
      "Sargento sliced cheese 6\u20138 oz",
      "Kraft sliced or shredded cheese 6\u20138 oz",
      "Tillamook sliced or shredded cheese 6\u20138 oz",
      "Tillamook shredded cheese",
      "Tillamook sliced cheese",
      "Tillamook cheese 6.5-8 oz",
      "Tillamook Shredded, Chunk, Sliced or Snack Cheese",
      "store-brand sliced or shredded cheese",
      "Sliced or shredded cheese"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "philadelphia_cream_cheese",
    "displayName": "Philadelphia cream cheese",
    "subtitle": "7.5\u20138 oz tubs or bricks",
    "displayOrder": 46,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "dairy",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Philadelphia cream cheese",
      "Philadelphia 1/3 less fat",
      "Philadelphia spread",
      "Philadelphia cream cheese"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "lucerne_cream_cheese",
    "displayName": "Lucerne cream cheese",
    "subtitle": "8 oz",
    "displayOrder": 47,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "dairy",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Lucerne cream cheese",
      "Lucerne cream cheese brick",
      "Lucerne cream cheese tub",
      "Lucerne cream cheese"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "chobani_yogurt_per_cup",
    "displayName": "Chobani yogurt cups",
    "subtitle": "single cups or 4\u00d75.3 oz multipacks (incl. Layered); normalize per cup",
    "displayOrder": 48,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "yogurt",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Chobani yogurt",
      "Chobani 5.3 oz",
      "Chobani Greek yogurt",
      "Chobani Greek",
      "Chobani Less Sugar",
      "Chobani Zero Sugar",
      "Less Sugar Yogurt",
      "Zero Sugar Yogurt",
      "Chobani 4-pack",
      "Chobani 4 ct",
      "Chobani Layered",
      "Chobani Flip",
      "Chobani Creations",
      "Chobani Complete",
      "Chobani yogurt"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "chobani_yogurt_tub",
    "displayName": "Chobani yogurt tub",
    "subtitle": "32 oz tub",
    "displayOrder": 49,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "yogurt",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Chobani 32 oz",
      "Chobani Greek yogurt tub",
      "Chobani yogurt tub"
    ],
    "legacyCanonicalIds": [
      "chobani_greek_yogurt"
    ],
    "displayCardGroup": ""
  },
  {
    "id": "fage_cups",
    "displayName": "Fage Greek yogurt cups",
    "subtitle": "5.3 oz cups",
    "displayOrder": 50,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "yogurt",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Fage cup",
      "Fage Greek yogurt 5.3 oz",
      "Fage Total cup",
      "Fage Greek yogurt cups"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "fage_tub",
    "displayName": "Fage Greek yogurt tub",
    "subtitle": "32 oz tub",
    "displayOrder": 51,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "yogurt",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Fage 32 oz",
      "Fage Total 32 oz",
      "Fage Greek yogurt tub",
      "Fage Greek yogurt tub"
    ],
    "legacyCanonicalIds": [
      "fage_greek_yogurt"
    ],
    "displayCardGroup": ""
  },
  {
    "id": "lucerne_yogurt_tubs",
    "displayName": "Lucerne yogurt tubs",
    "subtitle": "32 oz tubs",
    "displayOrder": 52,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "dairy",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Lucerne yogurt 32 oz",
      "Lucerne Greek yogurt tub",
      "Lucerne yogurt tubs"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "nature_valley_bars",
    "displayName": "Nature Valley bars",
    "subtitle": "roughly 5\u201312 ct boxes",
    "displayOrder": 53,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "bars_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Nature Valley Crunchy",
      "Nature Valley Sweet & Salty",
      "Nature Valley biscuits",
      "Nature Valley oatmeal squares",
      "Nature Valley bars",
      "Nature Valley bars"
    ],
    "legacyCanonicalIds": [
      "nature_valley_bars"
    ],
    "displayCardGroup": ""
  },
  {
    "id": "general_mills_cereal_regular",
    "displayName": "General Mills cereal",
    "subtitle": "regular size, 8.9\u201315 oz",
    "displayOrder": 54,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "cereal_breakfast",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Cheerios",
      "Cinnamon Toast Crunch",
      "Lucky Charms",
      "Chex cereal",
      "Reese's Puffs",
      "General Mills cereal",
      "Honey Nut Cheerios",
      "Honey Nut Cheerios cereal",
      "General Mills cereal"
    ],
    "legacyCanonicalIds": [
      "cheerios"
    ],
    "displayCardGroup": ""
  },
  {
    "id": "general_mills_cereal_family_size",
    "displayName": "General Mills cereal (family size)",
    "subtitle": "family size, 15\u201318 oz",
    "displayOrder": 55,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "cereal_breakfast",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "family size Cheerios",
      "family size Cinnamon Toast Crunch",
      "family size Lucky Charms",
      "family size Chex",
      "family size Honey Nut Cheerios",
      "Honey Nut Cheerios family size",
      "General Mills Family Size Cereal",
      "General Mills family size cereal",
      "Family Size Cereal",
      "General Mills cereal (family size)"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "post_cereal_regular",
    "displayName": "Post cereal",
    "subtitle": "regular size, 10\u201316 oz",
    "displayOrder": 56,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "cereal_breakfast",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Honey Bunches of Oats",
      "Pebbles",
      "Honeycomb",
      "Oreo O's",
      "Post cereal",
      "Post cereal"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "post_cereal_giant_size",
    "displayName": "Post cereal (giant size)",
    "subtitle": "family size, 21\u201324.7 oz",
    "displayOrder": 57,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "cereal_breakfast",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "giant-size Post cereal",
      "giant-size Honey Bunches of Oats",
      "giant-size Pebbles",
      "Post cereal (giant size)"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "thomas_bagels_muffins_bread",
    "displayName": "Thomas bagels / English muffins / swirl bread",
    "subtitle": "6 ct or roughly 12\u201318 oz",
    "displayOrder": 58,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "bakery",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Thomas bagels",
      "Thomas English muffins",
      "Thomas swirl bread",
      "Thomas breakfast bread",
      "Thomas bagels / English muffins / swirl bread"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "kings_hawaiian_rolls",
    "displayName": "King's Hawaiian rolls",
    "subtitle": "12 ct / 12 oz",
    "displayOrder": 59,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "bakery",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "King's Hawaiian Original rolls",
      "King's Hawaiian Savory Butter rolls",
      "King's Hawaiian slider rolls",
      "King's Hawaiian rolls"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "pillsbury_refrigerated_dough",
    "displayName": "Pillsbury ready-to-bake dough",
    "subtitle": "8\u201316.3 oz cans/tubes",
    "displayOrder": 60,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "refrigerated_bakery",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Pillsbury Grands",
      "Pillsbury biscuits",
      "Pillsbury crescent rolls",
      "Pillsbury cinnamon rolls",
      "Pillsbury cookie dough",
      "Pillsbury ready-to-bake dough"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "quest_bars",
    "displayName": "Quest bars",
    "subtitle": "single bars or multipacks; normalize per bar",
    "displayOrder": 61,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Quest bars",
      "Quest protein bars",
      "Quest Hero bars",
      "Quest snack bars",
      "Quest bars"
    ],
    "legacyCanonicalIds": [
      "protein_bars"
    ],
    "displayCardGroup": ""
  },
  {
    "id": "clif_bars",
    "displayName": "Clif Bars",
    "subtitle": "per bar (multipack price \u00f7 bar count)",
    "displayOrder": 62,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Clif bars",
      "Clif Kid Zbar",
      "Clif Nut Butter bars",
      "Clif Builders if intentionally included",
      "Clif bars"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "chicken_breast_per_lb",
    "displayName": "Chicken breast",
    "subtitle": "per lb",
    "displayOrder": 63,
    "homepageSection": "meat_and_seafood",
    "category": "meat",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "boneless skinless chicken breast",
      "boneless skinless chicken breasts",
      "chicken breast value pack",
      "chicken breasts",
      "chicken boneless skinless breasts",
      "chicken boneless skinless breast",
      "fresh chicken breast",
      "fresh chicken breasts",
      "Chicken breast"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "chicken_thigh_per_lb",
    "displayName": "Chicken thighs",
    "subtitle": "per lb",
    "displayOrder": 64,
    "homepageSection": "meat_and_seafood",
    "category": "meat",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "boneless skinless chicken thighs",
      "bone-in chicken thighs",
      "chicken thigh value pack",
      "fresh chicken thighs",
      "Chicken thighs"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "ribeye_steak",
    "displayName": "Ribeye steak",
    "subtitle": "per lb",
    "displayOrder": 66,
    "homepageSection": "meat_and_seafood",
    "category": "meat_seafood",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "ribeye steak",
      "bone-in ribeye",
      "USDA Choice ribeye",
      "Ribeye steak"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "tri_tip_roast",
    "displayName": "Tri-tip roast",
    "subtitle": "per lb",
    "displayOrder": 67,
    "homepageSection": "meat_and_seafood",
    "category": "meat_seafood",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "tri-tip roast",
      "tri tip roast",
      "trimmed tri-tip",
      "Tri-tip roast"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "salmon",
    "displayName": "Salmon",
    "subtitle": "fresh salmon fillet",
    "displayOrder": 68,
    "homepageSection": "meat_and_seafood",
    "category": "meat_seafood",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Atlantic salmon",
      "salmon fillets",
      "fresh salmon",
      "Fresh Atlantic Salmon Fillets",
      "salmon fillet",
      "salmon portion",
      "farm raised salmon",
      "Salmon"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "cape_cod_chips",
    "displayName": "Cape Cod potato chips",
    "subtitle": "regular size, 6.5\u20138.5 oz",
    "displayOrder": 69,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Cape Cod",
      "Cape Cod Chips",
      "Cape Cod Kettle Chips",
      "Cape Cod Kettle Cooked Potato Chips",
      "Cape Cod potato chips",
      "Cape Cod potato chips"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "smartfood_popcorn",
    "displayName": "Smartfood popcorn",
    "subtitle": "regular size, 4.75\u201311 oz",
    "displayOrder": 70,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Smartfood",
      "Smartfood Popcorn",
      "Smartfood White Cheddar",
      "Smartfood popcorn"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "pringles",
    "displayName": "Pringles",
    "subtitle": "regular cans, selected varieties",
    "displayOrder": 71,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Pringles",
      "Pringles Chips",
      "Pringles potato crisps",
      "Pringles"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "snyders_pretzels",
    "displayName": "Snyder's pretzels",
    "subtitle": "regular size, 10\u201316 oz",
    "displayOrder": 72,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Snyder's",
      "Snyder's Pretzels",
      "Snyders Pretzels",
      "Snyder's of Hanover",
      "Snyder's pretzels"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "frito_lay_multipack_chips",
    "displayName": "Frito-Lay variety pack",
    "subtitle": "18 ct multipack",
    "displayOrder": 73,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Frito-Lay Variety Pack",
      "Frito Lay Variety Pack",
      "Frito-Lay multipack",
      "Frito Lay Classic Mix Variety Pack",
      "Frito-Lay variety pack"
    ],
    "legacyCanonicalIds": [
      "frito_lay_multipack_chips"
    ],
    "displayCardGroup": ""
  },
  {
    "id": "pop_tarts",
    "displayName": "Pop-Tarts",
    "subtitle": "8 ct toaster pastries, selected varieties",
    "displayOrder": 74,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "cookies_crackers",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Pop-Tarts",
      "Kellogg's Pop-Tarts",
      "Kellogg Pop-Tarts",
      "Pop Tarts",
      "Pop-Tarts"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "kellogg_breakfast_bars",
    "displayName": "Nutri-Grain & Special K bars",
    "subtitle": "5\u201310 ct breakfast bars",
    "displayOrder": 75,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "bars_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Nutri-Grain",
      "Nutri Grain",
      "Kellogg's Nutri-Grain",
      "Nutri-Grain Bars",
      "Special K Bars",
      "Special K breakfast bars",
      "Nutri-Grain & Special K bars"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "betty_crocker_fruit_snacks",
    "displayName": "Gushers / Fruit by the Foot",
    "subtitle": "5\u201310 ct pouches (Gushers, Fruit by the Foot, selected)",
    "displayOrder": 76,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "bars_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Betty Crocker Fruit Snacks",
      "Betty Crocker fruit snacks",
      "Gushers",
      "Fruit Gushers",
      "Fruit by the Foot",
      "Fruit Roll-Ups",
      "Betty Crocker fruit snacks"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "waterloo_sparkling_water",
    "displayName": "Waterloo sparkling water",
    "subtitle": "8\u201312 pack, 12 fl oz cans",
    "displayOrder": 77,
    "homepageSection": "drinks",
    "category": "beverages",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Waterloo",
      "Waterloo Sparkling Water",
      "Waterloo sparkling water",
      "Waterloo sparkling water"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "bell_peppers",
    "displayName": "Bell peppers",
    "subtitle": "each or multi-buy",
    "displayOrder": 78,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Bell Pepper",
      "Bell Peppers",
      "Green Bell Peppers",
      "Green Bell Pepper",
      "Yellow Bell Pepper",
      "Red Bell Pepper",
      "Orange Bell Pepper",
      "Bell peppers"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "chicken_wings_per_lb",
    "displayName": "Chicken wings",
    "subtitle": "per lb (party wings)",
    "displayOrder": 79,
    "homepageSection": "meat_and_seafood",
    "category": "meat",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Chicken Party Wings",
      "Chicken Wings",
      "party wings",
      "fresh chicken wings",
      "Chicken wings"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "mandarins_3lb",
    "displayName": "Mandarin oranges (Cuties)",
    "subtitle": "3 lb bag",
    "displayOrder": 80,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Cuties Mandarins",
      "Cuties Mandarin Oranges",
      "Cuties",
      "California Mandarins",
      "mandarin oranges",
      "mandarins",
      "clementines",
      "clementine",
      "Mandarin oranges"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "beef_short_ribs_per_lb",
    "displayName": "Beef short ribs",
    "subtitle": "per lb",
    "displayOrder": 81,
    "homepageSection": "meat_and_seafood",
    "category": "meat_seafood",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Beef Chuck Short Ribs",
      "Beef Short Ribs",
      "short ribs",
      "Flanken Style Short Ribs",
      "flanken short ribs",
      "Beef short ribs"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "pork_spare_ribs_per_lb",
    "displayName": "Pork spare ribs",
    "subtitle": "per lb",
    "displayOrder": 82,
    "homepageSection": "meat_and_seafood",
    "category": "meat_seafood",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Pork Spareribs",
      "pork spare ribs",
      "spareribs",
      "St. Louis Style Pork Ribs",
      "St. Louis Style Pork Back Ribs",
      "St. Louis Style Pork Spareribs",
      "pork back ribs",
      "Pork spare ribs"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "oscar_mayer_hot_dogs",
    "displayName": "Oscar Mayer hot dogs",
    "subtitle": "15\u201316 oz packs",
    "displayOrder": 83,
    "homepageSection": "meat_and_seafood",
    "category": "meat",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Oscar Mayer Hot Dogs",
      "Oscar Mayer Beef Franks",
      "Oscar Mayer Franks",
      "Oscar Mayer Meat Franks",
      "Oscar Mayer hot dogs"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  },
  {
    "id": "cake_mix",
    "displayName": "Cake mix",
    "subtitle": "boxed mix ~15.25 oz, selected varieties",
    "displayOrder": 84,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "baking",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Cake Mix",
      "Pillsbury Cake Mix",
      "Pillsbury Moist Supreme Cake Mix",
      "Betty Crocker Cake Mix",
      "Duncan Hines Cake Mix",
      "devil's food cake mix",
      "Cake mix"
    ],
    "legacyCanonicalIds": [],
    "displayCardGroup": ""
  }
];

export const LEGACY_CANONICAL_TO_FAMILY: Record<string, string> = {
  "strawberries": "strawberries_1_2lb",
  "avocados": "hass_avocados_each",
  "doritos_nacho_cheese": "doritos_5_13oz",
  "cheetos_crunchy": "cheetos_regular_bags",
  "coke_zero": "coca_cola_12packs",
  "chobani_greek_yogurt": "chobani_yogurt_tub",
  "cheerios": "general_mills_cereal_regular",
  "tillamook_ice_cream": "tillamook_ice_cream",
  "mission_tortilla_chips": "tostitos_tortilla_chips",
  "nature_valley_bars": "nature_valley_bars",
  "fage_greek_yogurt": "fage_tub",
  "haagen_dazs_ice_cream": "haagen_dazs_pints",
  "grapes": "seedless_grapes_per_lb",
  "eggs_18_count": "eggs_dozen_normalized",
  "oreos_sandwich_cookies": "oreo_family_size",
  "kettle_brand_chips": "kettle_brand_chips",
  "ben_jerrys_ice_cream": "ben_jerrys_ice_cream",
  "ritz_crackers_snacks": "ritz_crackers",
  "frito_lay_multipack_chips": "frito_lay_multipack_chips",
  "protein_bars": "quest_bars"
};

export const POPULAR_THIS_WEEK_WEEK: string = "2026-07-29";

export const POPULAR_THIS_WEEK: Record<PopularThisWeekStore, PopularThisWeekEntry[]> = {
  safeway: [
  {
    "title": "Chobani yogurt cups",
    "trackerFamilyIds": [
      "chobani_yogurt_per_cup"
    ],
    "reason": "89\u00a2 when you buy 10 \u2014 near a recent low on single cups; mix Greek, Less Sugar, and Zero Sugar.",
    "subtitle": "89\u00a2 when you buy 10 \u2014 near a recent low on single cups; mix Greek, Less Sugar, and Zero Sugar.",
    "badge": "DEAL",
    "price": "$0.89",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 1
  },
  {
    "title": "Challenge / Danish Creamery butter",
    "trackerFamilyIds": [
      "butter_16oz"
    ],
    "reason": "$3.49 for 16 oz sticks \u2014 an all-time low on the butter chart this week.",
    "subtitle": "$3.49 for 16 oz sticks \u2014 an all-time low on the butter chart this week.",
    "badge": "DEAL",
    "price": "$3.49",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 2
  },
  {
    "title": "Honey mangoes",
    "trackerFamilyIds": [
      "mangoes_each"
    ],
    "reason": "10 for $10 ($1 each) \u2014 easy full-week tropical add-on.",
    "subtitle": "10 for $10 ($1 each) \u2014 easy full-week tropical add-on.",
    "badge": "PRODUCE",
    "price": "10/$10",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 3
  },
  {
    "title": "H\u00e4agen-Dazs ice cream",
    "trackerFamilyIds": [
      "haagen_dazs_pints"
    ],
    "reason": "$2.99 on 14 oz pints when you buy 3 \u2014 strong freezer stock-up.",
    "subtitle": "$2.99 on 14 oz pints when you buy 3 \u2014 strong freezer stock-up.",
    "badge": "DEAL",
    "price": "$2.99",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 4
  },
  {
    "title": "Doritos / Lay's / Tostitos",
    "trackerFamilyIds": [
      "doritos_5_13oz",
      "lays_potato_chips_regular",
      "tostitos_tortilla_chips"
    ],
    "reason": "Buy 2 Get 2 Free on 5\u201313 oz bags \u2014 effective about $2.75 when you use the full mix & match.",
    "subtitle": "Buy 2 Get 2 Free on 5\u201313 oz bags \u2014 effective about $2.75 when you use the full mix & match.",
    "badge": "SNACKS",
    "price": "B2G2F",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 5
  },
  {
    "title": "Ritz crackers",
    "trackerFamilyIds": [
      "ritz_crackers"
    ],
    "reason": "2 for $5 with belVita in the mix \u2014 solid cracker week.",
    "subtitle": "2 for $5 with belVita in the mix \u2014 solid cracker week.",
    "badge": "SNACKS",
    "price": "2/$5",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 6
  },
  {
    "title": "General Mills family-size cereal",
    "trackerFamilyIds": [
      "general_mills_cereal_family_size"
    ],
    "reason": "$3.99 family-size boxes on the Back-to-School 4x points tile.",
    "subtitle": "$3.99 family-size boxes on the Back-to-School 4x points tile.",
    "badge": "DEAL",
    "price": "$3.99",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 7
  },
  {
    "title": "Sweet corn",
    "trackerFamilyIds": [
      "sweet_corn"
    ],
    "reason": "Friday only \u2014 10 for $5 (50\u00a2 each) on local sweet corn.",
    "subtitle": "Friday only \u2014 10 for $5 (50\u00a2 each) on local sweet corn.",
    "badge": "FRIDAY",
    "price": "10/$5",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 8
  },
  {
    "title": "Hass avocados",
    "trackerFamilyIds": [
      "hass_avocados_each"
    ],
    "reason": "Friday only \u2014 4 for $5 ($1.25 each).",
    "subtitle": "Friday only \u2014 4 for $5 ($1.25 each).",
    "badge": "FRIDAY",
    "price": "4/$5",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 9
  },
  {
    "title": "Pringles",
    "trackerFamilyIds": [
      "pringles"
    ],
    "reason": "Friday only \u2014 3 for $5 on Pringles cans (mix with Signature SELECT chips).",
    "subtitle": "Friday only \u2014 3 for $5 on Pringles cans (mix with Signature SELECT chips).",
    "badge": "FRIDAY",
    "price": "3/$5",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 10
  },
  {
    "title": "Peaches, nectarines & plums",
    "trackerFamilyIds": [
      "plums_per_lb"
    ],
    "reason": "$2.99/lb on yellow peaches, nectarines, or black plums \u2014 local stone fruit.",
    "subtitle": "$2.99/lb on yellow peaches, nectarines, or black plums \u2014 local stone fruit.",
    "badge": "PRODUCE",
    "price": "$2.99/lb",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 11
  },
  {
    "title": "Large strawberries or blueberries",
    "trackerFamilyIds": [],
    "reason": "$4.99 on large-pack strawberries (2 lb) or blueberries (18 oz).",
    "subtitle": "$4.99 on large-pack strawberries (2 lb) or blueberries (18 oz).",
    "badge": "PRODUCE",
    "price": "$4.99",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 12
  }
],
  vons: [
  {
    "title": "Hand-picked deals updating soon",
    "trackerFamilyIds": [],
    "reason": "Safeway Jul 29\u2013Aug 4 is live \u2014 Vons hand-picked deals will update when that shortlist is curated.",
    "subtitle": "Safeway Jul 29\u2013Aug 4 is live \u2014 Vons hand-picked deals will update when that shortlist is curated.",
    "badge": "DEAL",
    "price": "Soon",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 1
  }
],
};
