// AUTO-GENERATED by scripts/generate_canonical_families.py; do not edit by hand.
// Source: data/canonical_tracker_families.yaml

export type HomepageSectionId =
  | "stock_up_snacks_and_treats"
  | "fresh_produce"
  | "dairy_breakfast_bakery"
  | "meat_and_seafood"
  | "drinks";

export type CanonicalTrackerFamily = {
  id: string;
  displayName: string;
  subtitle: string;
  displayOrder: number;
  homepageSection: HomepageSectionId;
  category: string;
  confidence: "high" | "medium" | "low" | "working";
  costcoComparable: boolean;
  searchAliases: string[];
  /** Old canonical_products ids whose historical rows map to this family. */
  legacyCanonicalIds: string[];
};

export type HomepageSection = {
  id: HomepageSectionId;
  label: string;
  order: number;
};

export type PopularThisWeekEntry = {
  title: string;
  trackerFamilyIds: string[];
  reason: string;
  /** Optional editorial subtitle override (curated shortlist cards). */
  subtitle: string;
  /** Optional editorial badge label override (e.g. FRIDAY, DEAL, MEAT). */
  badge: string;
  /** Curated editorial display price (effective_price or ad_price); empty for YAML/Vons cards. */
  price: string;
  /** Curated availability label, e.g. "Friday-only" or "Full week"; empty for YAML/Vons cards. */
  availability: string;
  /** True when the deal is a Friday-only editorial highlight. */
  fridayOnly: boolean;
  displayOrder: number;
};

export type PopularThisWeekStore = "safeway" | "vons";

export const HOMEPAGE_SECTIONS: HomepageSection[] = [
  {
    "id": "stock_up_snacks_and_treats",
    "label": "Snacks and Treats",
    "order": 1
  },
  {
    "id": "fresh_produce",
    "label": "Fresh produce",
    "order": 2
  },
  {
    "id": "dairy_breakfast_bakery",
    "label": "Dairy, breakfast & bakery",
    "order": 3
  },
  {
    "id": "meat_and_seafood",
    "label": "Meat & seafood",
    "order": 4
  },
  {
    "id": "drinks",
    "label": "Drinks",
    "order": 5
  }
];

export const CANONICAL_TRACKER_FAMILIES: CanonicalTrackerFamily[] = [
  {
    "id": "doritos_5_13oz",
    "displayName": "Doritos",
    "subtitle": "5\u201313 oz bags",
    "displayOrder": 1,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Doritos Nacho Cheese",
      "Doritos Cool Ranch",
      "Doritos Spicy Nacho",
      "Doritos Flamin Hot",
      "Doritos Dinamita",
      "Doritos limited edition flavors",
      "regular Doritos bags in size range",
      "Doritos"
    ],
    "legacyCanonicalIds": [
      "doritos_nacho_cheese"
    ]
  },
  {
    "id": "cheetos_regular_bags",
    "displayName": "Cheetos",
    "subtitle": "6.5\u201310 oz bags",
    "displayOrder": 2,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Cheetos Crunchy",
      "Cheetos Puffs",
      "Cheetos Popcorn",
      "Cheetos Flamin Hot",
      "Cheetos Extra Flamin Hot",
      "Cheetos Crunchy Flamin Hot Dill Pickle",
      "Cheetos Cheddar Jalape\u00f1o",
      "regular Cheetos bags in size range",
      "Cheetos"
    ],
    "legacyCanonicalIds": [
      "cheetos_crunchy"
    ]
  },
  {
    "id": "cheetos_party_size",
    "displayName": "Cheetos Party Size",
    "subtitle": "roughly 15 oz bags",
    "displayOrder": 3,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Cheetos Party Size",
      "Cheetos Party Size"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "lays_potato_chips_regular",
    "displayName": "Lay's potato chips",
    "subtitle": "regular non-kettle bags, roughly 5\u201313 oz",
    "displayOrder": 4,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Lay's Classic",
      "Lay's Barbecue",
      "Lay's Sour Cream & Onion",
      "Lay's Lim\u00f3n",
      "Lay's Salt & Vinegar",
      "Lay's Dill Pickle",
      "Lay's Cheddar & Sour Cream",
      "Lay's potato chips"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "lays_kettle_cooked",
    "displayName": "Lay's Kettle Cooked chips",
    "subtitle": "7.75 oz bags",
    "displayOrder": 5,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Lay's Kettle Cooked Original",
      "Lay's Kettle Cooked Jalape\u00f1o",
      "Lay's Kettle Cooked BBQ",
      "Lay's Kettle Cooked Sea Salt & Vinegar",
      "Lay's Kettle Cooked Cajun Spiced",
      "Lay's Kettle Cooked chips"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "lays_party_size",
    "displayName": "Lay's Party Size",
    "subtitle": "roughly 12.5\u201313 oz bags",
    "displayOrder": 6,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Lay's Party Size",
      "Lay's Party Size"
    ],
    "legacyCanonicalIds": [
      "frito_lay_multipack_chips"
    ]
  },
  {
    "id": "kettle_brand_chips",
    "displayName": "Kettle Brand potato chips",
    "subtitle": "6.5\u20138.5 oz bags",
    "displayOrder": 7,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Kettle Brand Sea Salt",
      "Kettle Brand Jalape\u00f1o",
      "Kettle Brand Backyard Barbeque",
      "Kettle Brand Salt & Vinegar",
      "Kettle Brand Honey Dijon",
      "Kettle Brand Chips",
      "Kettle Brand potato chips",
      "Kettle Brand potato chips"
    ],
    "legacyCanonicalIds": [
      "kettle_brand_chips"
    ]
  },
  {
    "id": "ruffles_regular_bags",
    "displayName": "Ruffles",
    "subtitle": "regular bags, roughly 5\u201313 oz",
    "displayOrder": 8,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Ruffles Original",
      "Ruffles Cheddar & Sour Cream",
      "Ruffles Sour Cream & Onion",
      "Ruffles Flamin' Hot",
      "Ruffles potato chips",
      "Ruffles"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "sun_chips_7oz",
    "displayName": "Sun Chips",
    "subtitle": "7 oz bags",
    "displayOrder": 9,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Sun Chips Original",
      "Sun Chips Harvest Cheddar",
      "Sun Chips Garden Salsa",
      "Sun Chips French Onion",
      "Sun Chips 7 oz bags",
      "Sun Chips"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "tostitos_tortilla_chips",
    "displayName": "Tostitos tortilla chips",
    "subtitle": "roughly 9\u201313 oz bags",
    "displayOrder": 10,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Tostitos Scoops",
      "Tostitos Restaurant Style",
      "Tostitos Cantina",
      "Tostitos tortilla chips",
      "Tostitos tortilla chips"
    ],
    "legacyCanonicalIds": [
      "mission_tortilla_chips"
    ]
  },
  {
    "id": "simply_snacks",
    "displayName": "Simply snacks",
    "subtitle": "Simply-branded bags, roughly 4.5\u201313 oz",
    "displayOrder": 11,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Simply Cheetos",
      "Simply Cheetos Puffs",
      "Simply Doritos",
      "Simply Lay's",
      "Simply Ruffles",
      "Simply Popables",
      "Simply snacks"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "simply_party_size",
    "displayName": "Simply Party Size",
    "subtitle": "larger Simply bags, roughly 10\u201311 oz",
    "displayOrder": 12,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "chips_salty_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Simply Party Size",
      "Simply large bags",
      "Simply Party Size"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "ritz_crackers",
    "displayName": "Ritz crackers",
    "subtitle": "8.8\u201313.7 oz boxes",
    "displayOrder": 13,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "cookies_crackers",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Ritz Original",
      "Ritz Fresh Stacks",
      "Ritz Crisp & Thins",
      "Ritz Bits",
      "Ritz Drizzled Minis",
      "Ritz crackers"
    ],
    "legacyCanonicalIds": [
      "ritz_crackers_snacks"
    ]
  },
  {
    "id": "ritz_toasted_chips",
    "displayName": "Nabisco Ritz Toasted Chips",
    "subtitle": "7\u20138.1 oz bags",
    "displayOrder": 14,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "cookies_crackers",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Ritz Toasted Chips",
      "Nabisco Ritz Toasted Chips"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "nabisco_snack_crackers",
    "displayName": "Wheat Thins, Triscuit & Chicken in a Biskit",
    "subtitle": "Nabisco family-size snack crackers, 11.5\u201314 oz",
    "displayOrder": 15,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "cookies_crackers",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Wheat Thins",
      "Wheat Thins Family Size",
      "Triscuit",
      "Triscuit Family Size",
      "Chicken in a Biskit",
      "Chicken in a Biskit Family Size",
      "Nabisco Snack Crackers Family Size",
      "Nabisco snack crackers",
      "Wheat Thins, Triscuit & Chicken in a Biskit"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "cheez_it_crackers",
    "displayName": "Cheez-It crackers",
    "subtitle": "6.5\u201312.4 oz boxes/bags",
    "displayOrder": 16,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "cookies_crackers",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Cheez-It Original",
      "Cheez-It White Cheddar",
      "Cheez-It Extra Toasty",
      "Cheez-It Snap'd",
      "Cheez-It Puff'd",
      "Cheez-It crackers"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "chips_ahoy",
    "displayName": "Chips Ahoy cookies",
    "subtitle": "9.5\u201313 oz packages",
    "displayOrder": 17,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "cookies_crackers",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Chips Ahoy Original",
      "Chips Ahoy Chewy",
      "Chips Ahoy Chunky",
      "Chips Ahoy Mini",
      "Chips Ahoy limited edition flavors",
      "Chips Ahoy cookies"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "oreo_family_size",
    "displayName": "Oreo cookies",
    "subtitle": "family size, roughly 10.68\u201318.71 oz",
    "displayOrder": 18,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "cookies_crackers",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Oreo Original",
      "Oreo Double Stuf",
      "Oreo Golden",
      "Oreo Thins",
      "Oreo limited edition flavors",
      "family size Oreo",
      "Oreo cookies"
    ],
    "legacyCanonicalIds": [
      "oreos_sandwich_cookies"
    ]
  },
  {
    "id": "goldfish_bags",
    "displayName": "Goldfish",
    "subtitle": "6\u20138 oz bags",
    "displayOrder": 19,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "crackers_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Goldfish crackers",
      "Goldfish crisps",
      "Goldfish flavor blasted",
      "Goldfish bags in size range",
      "Goldfish"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "keebler_sandwich_crackers",
    "displayName": "Keebler sandwich crackers",
    "subtitle": "8-pack boxes",
    "displayOrder": 20,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "cookies_crackers",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Keebler sandwich crackers",
      "Keebler cheese crackers",
      "Keebler peanut butter crackers",
      "Keebler sandwich crackers"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "coca_cola_12packs",
    "displayName": "Coca-Cola",
    "subtitle": "12-pack, 12 fl oz cans",
    "displayOrder": 21,
    "homepageSection": "drinks",
    "category": "beverages",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Coca-Cola 12-pack",
      "Coke 12-pack",
      "Coke Zero 12-pack",
      "Diet Coke 12-pack",
      "Sprite only if ad groups under Coca-Cola family and user approves",
      "Coca-Cola"
    ],
    "legacyCanonicalIds": [
      "coke_zero"
    ]
  },
  {
    "id": "pepsi_12packs",
    "displayName": "Pepsi",
    "subtitle": "12-pack, 12 fl oz cans",
    "displayOrder": 22,
    "homepageSection": "drinks",
    "category": "beverages",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Pepsi 12-pack",
      "Diet Pepsi 12-pack",
      "Pepsi Zero 12-pack",
      "Pepsi"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "dr_pepper_12packs",
    "displayName": "Dr Pepper",
    "subtitle": "12-pack, 12 fl oz cans",
    "displayOrder": 23,
    "homepageSection": "drinks",
    "category": "beverages",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Dr Pepper 12-pack",
      "Diet Dr Pepper 12-pack",
      "Dr Pepper Zero Sugar 12-pack",
      "Dr Pepper"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "lacroix_8pack",
    "displayName": "LaCroix sparkling water",
    "subtitle": "8-pack, 12 fl oz cans",
    "displayOrder": 24,
    "homepageSection": "drinks",
    "category": "beverages",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "LaCroix",
      "La Croix",
      "LaCroix sparkling water",
      "LaCroix 8-pack",
      "LaCroix sparkling water"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "simply_refrigerated_juice_lemonade",
    "displayName": "Simply juice",
    "subtitle": "46\u201352 fl oz bottles",
    "displayOrder": 25,
    "homepageSection": "drinks",
    "category": "beverages",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Simply Lemonade",
      "Simply Juice Drink",
      "Simply Orange",
      "Simply Light Orange",
      "Simply Limeade",
      "Simply juice"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "haagen_dazs_pints",
    "displayName": "H\u00e4agen-Dazs ice cream pints",
    "subtitle": "14 oz pints",
    "displayOrder": 26,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "ice_cream",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "H\u00e4agen-Dazs pint",
      "Haagen Dazs pint",
      "H\u00e4agen-Dazs 14 oz",
      "H\u00e4agen-Dazs ice cream",
      "Haagen Dazs ice cream",
      "H\u00e4agen-Dazs ice cream pints"
    ],
    "legacyCanonicalIds": [
      "haagen_dazs_ice_cream"
    ]
  },
  {
    "id": "ben_jerrys_ice_cream",
    "displayName": "Ben & Jerry's ice cream",
    "subtitle": "pints, non-dairy pints, or 4 ct bars",
    "displayOrder": 27,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "ice_cream",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Ben & Jerry's pint",
      "Ben and Jerry's",
      "B&J",
      "non-dairy pints",
      "Ben & Jerry's bars",
      "Ben & Jerry's ice cream"
    ],
    "legacyCanonicalIds": [
      "ben_jerrys_ice_cream"
    ]
  },
  {
    "id": "dreyers_tubs",
    "displayName": "Dreyer's ice cream",
    "subtitle": "1.5 qt tubs",
    "displayOrder": 28,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "ice_cream",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Dreyer's ice cream",
      "Dreyers ice cream",
      "Dreyer's 1.5 qt",
      "Dreyer's ice cream"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "breyers_ice_cream",
    "displayName": "Breyers ice cream",
    "subtitle": "tubs, including Carb Smart and Sunday Swirls",
    "displayOrder": 29,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "ice_cream",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Breyers",
      "Breyers Carb Smart",
      "Breyers Sunday Swirls",
      "Breyers Natural Vanilla",
      "Breyers ice cream"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "tillamook_ice_cream",
    "displayName": "Tillamook ice cream",
    "subtitle": "1.5 qt tubs or 4 ct bars when grouped",
    "displayOrder": 30,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "ice_cream",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Tillamook ice cream",
      "Tillamook 1.5 qt",
      "Tillamook bars",
      "Tillamook ice cream"
    ],
    "legacyCanonicalIds": [
      "tillamook_ice_cream"
    ]
  },
  {
    "id": "haagen_dazs_bars_novelties",
    "displayName": "H\u00e4agen-Dazs bars / novelties",
    "subtitle": "3\u20134 ct boxes",
    "displayOrder": 31,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "ice_cream",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "H\u00e4agen-Dazs bars",
      "H\u00e4agen-Dazs cones",
      "Haagen Dazs novelties",
      "H\u00e4agen-Dazs bars / novelties"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "dreyers_novelties",
    "displayName": "Dreyer's novelties",
    "subtitle": "4 ct boxes",
    "displayOrder": 32,
    "homepageSection": "stock_up_snacks_and_treats",
    "category": "ice_cream",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Dreyer's bars",
      "Dreyer's cones",
      "Dreyer's novelties 4 ct",
      "Dreyer's novelties"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "strawberries_1_2lb",
    "displayName": "Strawberries",
    "subtitle": "1 lb or 2 lb packs; normalize per lb",
    "displayOrder": 33,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "conventional strawberries 1 lb",
      "conventional strawberries 2 lb",
      "fresh strawberries",
      "strawberry clamshells",
      "Strawberries"
    ],
    "legacyCanonicalIds": [
      "strawberries"
    ]
  },
  {
    "id": "seedless_grapes_per_lb",
    "displayName": "Seedless grapes",
    "subtitle": "per lb; normalize bags to per lb",
    "displayOrder": 34,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "red seedless grapes",
      "green seedless grapes",
      "seedless grapes per lb",
      "3 lb seedless grape bags when advertised",
      "Seedless grapes"
    ],
    "legacyCanonicalIds": [
      "grapes"
    ]
  },
  {
    "id": "cherries_per_lb",
    "displayName": "Cherries",
    "subtitle": "per lb",
    "displayOrder": 35,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "red cherries",
      "cherries per lb",
      "fresh cherries",
      "Cherries"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "berries_6oz",
    "displayName": "Blueberries / raspberries / blackberries",
    "subtitle": "6 oz clamshells",
    "displayOrder": 36,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "blueberries",
      "raspberries",
      "blackberries",
      "blueberries 6 oz",
      "raspberries 6 oz",
      "blackberries 6 oz",
      "berries 6 oz",
      "Blueberries / raspberries / blackberries"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "hass_avocados_each",
    "displayName": "Hass avocados",
    "subtitle": "each or multi-buy",
    "displayOrder": 37,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Hass avocado",
      "Hass avocados",
      "avocado each",
      "avocados 4 for",
      "Hass avocados"
    ],
    "legacyCanonicalIds": [
      "avocados"
    ]
  },
  {
    "id": "mangoes_each",
    "displayName": "Mangoes",
    "subtitle": "each or multi-buy",
    "displayOrder": 38,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "mango",
      "mangoes",
      "large mangoes",
      "mango each",
      "Mangoes"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "peaches_per_lb",
    "displayName": "Peaches",
    "subtitle": "per lb",
    "displayOrder": 39,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "yellow peaches",
      "white peaches",
      "fresh peaches",
      "peaches per lb",
      "Peaches"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "nectarines_per_lb",
    "displayName": "Nectarines",
    "subtitle": "per lb",
    "displayOrder": 40,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "yellow nectarines",
      "white nectarines",
      "fresh nectarines",
      "nectarines per lb",
      "Nectarines"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "plums_per_lb",
    "displayName": "Plums",
    "subtitle": "per lb",
    "displayOrder": 41,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "red plums",
      "black plums",
      "fresh plums",
      "plums per lb",
      "Plums"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "sweet_corn",
    "displayName": "Sweet corn",
    "subtitle": "each or multi-buy",
    "displayOrder": 42,
    "homepageSection": "fresh_produce",
    "category": "produce",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "sweet corn",
      "corn on the cob",
      "corn 8 for",
      "corn 3 for",
      "Sweet corn"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "eggs_dozen_normalized",
    "displayName": "Eggs",
    "subtitle": "per dozen (18/24 ct packs scaled to 12)",
    "displayOrder": 43,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "dairy",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "large eggs",
      "large eggs 12 ct",
      "large eggs 18 ct",
      "large eggs 24 ct",
      "Lucerne eggs",
      "Lucerne Large Eggs",
      "Eggland's Best",
      "Happy Egg",
      "dozen eggs",
      "cage free eggs",
      "free range eggs",
      "Large eggs"
    ],
    "legacyCanonicalIds": [
      "eggs_18_count"
    ]
  },
  {
    "id": "butter_16oz",
    "displayName": "Butter",
    "subtitle": "16 oz sticks / quarters; normalize to 16 oz",
    "displayOrder": 44,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "dairy",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Lucerne butter 16 oz",
      "Challenge butter 16 oz",
      "Land O Lakes butter 16 oz",
      "Kerrygold butter when comparable size or normalized",
      "store-brand butter 16 oz",
      "name-brand butter 16 oz",
      "Butter"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "sliced_or_shredded_cheese_6_8oz",
    "displayName": "Sliced or shredded cheese",
    "subtitle": "6\u20138 oz packages",
    "displayOrder": 45,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "dairy",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Lucerne shredded cheese 6\u20138 oz",
      "Lucerne sliced cheese 6\u20138 oz",
      "Sargento shredded cheese 6\u20138 oz",
      "Sargento sliced cheese 6\u20138 oz",
      "Kraft sliced or shredded cheese 6\u20138 oz",
      "Tillamook sliced or shredded cheese 6\u20138 oz",
      "store-brand sliced or shredded cheese",
      "Sliced or shredded cheese"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "philadelphia_cream_cheese",
    "displayName": "Philadelphia cream cheese",
    "subtitle": "7.5\u20138 oz tubs or bricks",
    "displayOrder": 46,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "dairy",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Philadelphia cream cheese",
      "Philadelphia 1/3 less fat",
      "Philadelphia spread",
      "Philadelphia cream cheese"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "lucerne_cream_cheese",
    "displayName": "Lucerne cream cheese",
    "subtitle": "8 oz",
    "displayOrder": 47,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "dairy",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Lucerne cream cheese",
      "Lucerne cream cheese brick",
      "Lucerne cream cheese tub",
      "Lucerne cream cheese"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "chobani_yogurt_per_cup",
    "displayName": "Chobani yogurt",
    "subtitle": "single cups or 4-packs; normalize per cup",
    "displayOrder": 48,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "yogurt",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Chobani 5.3 oz cups",
      "Chobani Greek yogurt cups",
      "Chobani Less Sugar cups",
      "Chobani Zero Sugar cups",
      "Chobani 4-packs",
      "Chobani yogurt"
    ],
    "legacyCanonicalIds": [
      "chobani_greek_yogurt"
    ]
  },
  {
    "id": "fage_cups",
    "displayName": "Fage Greek yogurt cups",
    "subtitle": "5.3 oz cups",
    "displayOrder": 49,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "yogurt",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Fage cup",
      "Fage Greek yogurt 5.3 oz",
      "Fage Total cup",
      "Fage Greek yogurt cups"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "fage_tub",
    "displayName": "Fage Greek yogurt tub",
    "subtitle": "32 oz tub",
    "displayOrder": 50,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "yogurt",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Fage 32 oz",
      "Fage Total 32 oz",
      "Fage Greek yogurt tub",
      "Fage Greek yogurt tub"
    ],
    "legacyCanonicalIds": [
      "fage_greek_yogurt"
    ]
  },
  {
    "id": "lucerne_yogurt_tubs",
    "displayName": "Lucerne yogurt tubs",
    "subtitle": "32 oz tubs",
    "displayOrder": 51,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "dairy",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Lucerne yogurt 32 oz",
      "Lucerne Greek yogurt tub",
      "Lucerne yogurt tubs"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "nature_valley_bars",
    "displayName": "Nature Valley bars",
    "subtitle": "roughly 5\u201312 ct boxes",
    "displayOrder": 52,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "bars_snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Nature Valley Crunchy",
      "Nature Valley Sweet & Salty",
      "Nature Valley biscuits",
      "Nature Valley oatmeal squares",
      "Nature Valley bars",
      "Nature Valley bars"
    ],
    "legacyCanonicalIds": [
      "nature_valley_bars"
    ]
  },
  {
    "id": "general_mills_cereal_regular",
    "displayName": "General Mills cereal",
    "subtitle": "regular boxes, roughly 8.9\u201315 oz",
    "displayOrder": 53,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "cereal_breakfast",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Cheerios",
      "Cinnamon Toast Crunch",
      "Lucky Charms",
      "Chex cereal",
      "Reese's Puffs",
      "General Mills cereal",
      "General Mills cereal"
    ],
    "legacyCanonicalIds": [
      "cheerios"
    ]
  },
  {
    "id": "general_mills_cereal_family_size",
    "displayName": "General Mills cereal (family size)",
    "subtitle": "family-size boxes, roughly 15\u201318 oz",
    "displayOrder": 54,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "cereal_breakfast",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "family size Cheerios",
      "family size Cinnamon Toast Crunch",
      "family size Lucky Charms",
      "family size Chex",
      "General Mills cereal (family size)"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "post_cereal_regular",
    "displayName": "Post cereal",
    "subtitle": "regular boxes, roughly 10\u201316 oz",
    "displayOrder": 55,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "cereal_breakfast",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Honey Bunches of Oats",
      "Pebbles",
      "Honeycomb",
      "Oreo O's",
      "Post cereal",
      "Post cereal"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "post_cereal_giant_size",
    "displayName": "Post cereal (giant size)",
    "subtitle": "giant-size boxes, roughly 21\u201324.7 oz",
    "displayOrder": 56,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "cereal_breakfast",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "giant-size Post cereal",
      "giant-size Honey Bunches of Oats",
      "giant-size Pebbles",
      "Post cereal (giant size)"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "thomas_bagels_muffins_bread",
    "displayName": "Thomas bagels / English muffins / swirl bread",
    "subtitle": "6 ct or roughly 12\u201318 oz",
    "displayOrder": 57,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "bakery",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Thomas bagels",
      "Thomas English muffins",
      "Thomas swirl bread",
      "Thomas breakfast bread",
      "Thomas bagels / English muffins / swirl bread"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "kings_hawaiian_rolls",
    "displayName": "King's Hawaiian rolls",
    "subtitle": "12 ct / 12 oz",
    "displayOrder": 58,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "bakery",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "King's Hawaiian Original rolls",
      "King's Hawaiian Savory Butter rolls",
      "King's Hawaiian slider rolls",
      "King's Hawaiian rolls"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "pillsbury_refrigerated_dough",
    "displayName": "Pillsbury ready-to-bake dough",
    "subtitle": "8\u201316.3 oz cans/tubes",
    "displayOrder": 59,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "refrigerated_bakery",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Pillsbury Grands",
      "Pillsbury biscuits",
      "Pillsbury crescent rolls",
      "Pillsbury cinnamon rolls",
      "Pillsbury cookie dough",
      "Pillsbury ready-to-bake dough"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "quest_bars",
    "displayName": "Quest bars",
    "subtitle": "single bars or multipacks; normalize per bar",
    "displayOrder": 60,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Quest bars",
      "Quest protein bars",
      "Quest Hero bars",
      "Quest snack bars",
      "Quest bars"
    ],
    "legacyCanonicalIds": [
      "protein_bars"
    ]
  },
  {
    "id": "clif_bars",
    "displayName": "Clif Bars",
    "subtitle": "per bar (multipack price \u00f7 bar count)",
    "displayOrder": 61,
    "homepageSection": "dairy_breakfast_bakery",
    "category": "snacks",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Clif bars",
      "Clif Kid Zbar",
      "Clif Nut Butter bars",
      "Clif Builders if intentionally included",
      "Clif bars"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "chicken_breast_per_lb",
    "displayName": "Chicken breast",
    "subtitle": "per lb",
    "displayOrder": 62,
    "homepageSection": "meat_and_seafood",
    "category": "meat",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "boneless skinless chicken breast",
      "chicken breast value pack",
      "fresh chicken breast",
      "Chicken breast"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "chicken_thigh_per_lb",
    "displayName": "Chicken thighs",
    "subtitle": "per lb",
    "displayOrder": 63,
    "homepageSection": "meat_and_seafood",
    "category": "meat",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "boneless skinless chicken thighs",
      "bone-in chicken thighs",
      "chicken thigh value pack",
      "fresh chicken thighs",
      "Chicken thighs"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "ribeye_steak",
    "displayName": "Ribeye steak",
    "subtitle": "per lb",
    "displayOrder": 64,
    "homepageSection": "meat_and_seafood",
    "category": "meat_seafood",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "ribeye steak",
      "bone-in ribeye",
      "USDA Choice ribeye",
      "Ribeye steak"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "tri_tip_roast",
    "displayName": "Tri-tip roast",
    "subtitle": "per lb",
    "displayOrder": 65,
    "homepageSection": "meat_and_seafood",
    "category": "meat_seafood",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "tri-tip roast",
      "tri tip roast",
      "trimmed tri-tip",
      "Tri-tip roast"
    ],
    "legacyCanonicalIds": []
  },
  {
    "id": "salmon",
    "displayName": "Salmon",
    "subtitle": "fresh salmon fillet",
    "displayOrder": 66,
    "homepageSection": "meat_and_seafood",
    "category": "meat_seafood",
    "confidence": "working",
    "costcoComparable": true,
    "searchAliases": [
      "Atlantic salmon",
      "salmon fillets",
      "fresh salmon",
      "Fresh Atlantic Salmon Fillets",
      "salmon fillet",
      "salmon portion",
      "farm raised salmon",
      "Salmon"
    ],
    "legacyCanonicalIds": []
  }
];

export const LEGACY_CANONICAL_TO_FAMILY: Record<string, string> = {
  "strawberries": "strawberries_1_2lb",
  "avocados": "hass_avocados_each",
  "doritos_nacho_cheese": "doritos_5_13oz",
  "cheetos_crunchy": "cheetos_regular_bags",
  "coke_zero": "coca_cola_12packs",
  "chobani_greek_yogurt": "chobani_yogurt_per_cup",
  "cheerios": "general_mills_cereal_regular",
  "tillamook_ice_cream": "tillamook_ice_cream",
  "mission_tortilla_chips": "tostitos_tortilla_chips",
  "nature_valley_bars": "nature_valley_bars",
  "fage_greek_yogurt": "fage_tub",
  "haagen_dazs_ice_cream": "haagen_dazs_pints",
  "grapes": "seedless_grapes_per_lb",
  "eggs_18_count": "eggs_dozen_normalized",
  "oreos_sandwich_cookies": "oreo_family_size",
  "kettle_brand_chips": "kettle_brand_chips",
  "ben_jerrys_ice_cream": "ben_jerrys_ice_cream",
  "ritz_crackers_snacks": "ritz_crackers",
  "frito_lay_multipack_chips": "lays_party_size",
  "protein_bars": "quest_bars"
};

export const POPULAR_THIS_WEEK_WEEK: string = "2026-07-08";

export const POPULAR_THIS_WEEK: Record<PopularThisWeekStore, PopularThisWeekEntry[]> = {
  safeway: [
  {
    "title": "Hass avocados",
    "trackerFamilyIds": [],
    "reason": "99\u00a2 each, about 26% cheaper than Costco; for about Costco's 6-pack price, you can get roughly 8 at Safeway.",
    "subtitle": "99\u00a2 each, about 26% cheaper than Costco; for about Costco's 6-pack price, you can get roughly 8 at Safeway.",
    "badge": "DEAL",
    "price": "$0.99 each",
    "availability": "Full week",
    "fridayOnly": false,
    "displayOrder": 1
  },
  {
    "title": "Berries",
    "trackerFamilyIds": [],
    "reason": "Best on blackberries at about 30% cheaper than Costco; raspberries and blueberries also look 15\u201320% cheaper.",
    "subtitle": "Best on blackberries at about 30% cheaper than Costco; raspberries and blueberries also look 15\u201320% cheaper.",
    "badge": "PRODUCE",
    "price": "$2.99 each",
    "availability": "Full week",
    "fridayOnly": false,
    "displayOrder": 2
  },
  {
    "title": "Chobani yogurt",
    "trackerFamilyIds": [],
    "reason": "Cheaper than Costco; with the 4-pack deal, Costco's 16-pack price gets you almost 22 at Safeway.",
    "subtitle": "Cheaper than Costco; with the 4-pack deal, Costco's 16-pack price gets you almost 22 at Safeway.",
    "badge": "DEAL",
    "price": "$0.99 each / $3.49 4-pack",
    "availability": "Full week",
    "fridayOnly": false,
    "displayOrder": 3
  },
  {
    "title": "Frozen shrimp",
    "trackerFamilyIds": [],
    "reason": "Friday-only: Frozen shrimp is about 30% cheaper than Costco.",
    "subtitle": "Friday-only: Frozen shrimp is about 30% cheaper than Costco.",
    "badge": "FRIDAY",
    "price": "$5/lb",
    "availability": "Friday-only",
    "fridayOnly": true,
    "displayOrder": 4
  },
  {
    "title": "Bell peppers",
    "trackerFamilyIds": [],
    "reason": "Friday-only: Bell peppers are about 30% cheaper than Costco.",
    "subtitle": "Friday-only: Bell peppers are about 30% cheaper than Costco.",
    "badge": "FRIDAY",
    "price": "$1 each",
    "availability": "Friday-only",
    "fridayOnly": true,
    "displayOrder": 5
  },
  {
    "title": "Nestl\u00e9 Drumstick ice cream",
    "trackerFamilyIds": [],
    "reason": "Friday-only: about 17% cheaper than Costco, plus a variety win.",
    "subtitle": "Friday-only: about 17% cheaper than Costco, plus a variety win.",
    "badge": "FRIDAY",
    "price": "$5 each",
    "availability": "Friday-only",
    "fridayOnly": true,
    "displayOrder": 6
  },
  {
    "title": "Pork shoulder ribs",
    "trackerFamilyIds": [],
    "reason": "About 21% cheaper than Costco, one of the stronger meat-counter comparisons.",
    "subtitle": "About 21% cheaper than Costco, one of the stronger meat-counter comparisons.",
    "badge": "MEAT",
    "price": "$2.99/lb",
    "availability": "Full week",
    "fridayOnly": false,
    "displayOrder": 7
  },
  {
    "title": "Oreo / Nabisco snacks",
    "trackerFamilyIds": [],
    "reason": "Good time to buy Oreos; the smaller Safeway buy is close enough to Costco that variety matters.",
    "subtitle": "Good time to buy Oreos; the smaller Safeway buy is close enough to Costco that variety matters.",
    "badge": "SNACKS",
    "price": "$3.49 each when you buy 2",
    "availability": "Full week",
    "fridayOnly": false,
    "displayOrder": 8
  },
  {
    "title": "Doritos / snack bags",
    "trackerFamilyIds": [],
    "reason": "Friday-only: close to Costco pricing, but Safeway wins on smaller bags and flavor variety.",
    "subtitle": "Friday-only: close to Costco pricing, but Safeway wins on smaller bags and flavor variety.",
    "badge": "VARIETY",
    "price": "$2.50 each",
    "availability": "Friday-only",
    "fridayOnly": true,
    "displayOrder": 9
  },
  {
    "title": "Beef chuck short ribs",
    "trackerFamilyIds": [],
    "reason": "Not an exact same-grade match, but Safeway looks cheaper across the comparable Costco short rib options.",
    "subtitle": "Not an exact same-grade match, but Safeway looks cheaper across the comparable Costco short rib options.",
    "badge": "MEAT",
    "price": "$7.99/lb",
    "availability": "Full week",
    "fridayOnly": false,
    "displayOrder": 10
  },
  {
    "title": "Sargento cheese",
    "trackerFamilyIds": [],
    "reason": "Down to nearly a third of regular retail pricing.",
    "subtitle": "Down to nearly a third of regular retail pricing.",
    "badge": "DEAL",
    "price": "$4.99 each",
    "availability": "Full week",
    "fridayOnly": false,
    "displayOrder": 11
  },
  {
    "title": "Oreo variety angle",
    "trackerFamilyIds": [],
    "reason": "Costco may be a little cheaper on bulk, but with a gap under 10%, Safeway wins on smaller buy and variety.",
    "subtitle": "Costco may be a little cheaper on bulk, but with a gap under 10%, Safeway wins on smaller buy and variety.",
    "badge": "VARIETY",
    "price": "$3.49 each when you buy 2",
    "availability": "Full week",
    "fridayOnly": false,
    "displayOrder": 12
  }
],
  vons: [
  {
    "title": "Cheez-It crackers",
    "trackerFamilyIds": [
      "cheez_it_crackers"
    ],
    "reason": "$5 Friday win: grab the bigger Cheez-It boxes and Vons can beat Costco by around 30% per ounce, with way more flavors to choose from.",
    "subtitle": "$5 Friday win: grab the bigger Cheez-It boxes and Vons can beat Costco by around 30% per ounce, with way more flavors to choose from.",
    "badge": "FRIDAY",
    "price": "3 for $5",
    "availability": "Friday-only",
    "fridayOnly": true,
    "displayOrder": 1
  },
  {
    "title": "Post cereal",
    "trackerFamilyIds": [
      "post_cereal_regular"
    ],
    "reason": "Post cereal is 3 for $5 on Friday. Honey Bunches of Oats comes out a little over 10% cheaper than Costco, and you get way more variety.",
    "subtitle": "Post cereal is 3 for $5 on Friday. Honey Bunches of Oats comes out a little over 10% cheaper than Costco, and you get way more variety.",
    "badge": "FRIDAY",
    "price": "3 for $5",
    "availability": "Friday-only",
    "fridayOnly": true,
    "displayOrder": 2
  },
  {
    "title": "Lucerne cheese",
    "trackerFamilyIds": [
      "sliced_or_shredded_cheese_6_8oz"
    ],
    "reason": "Lucerne cheese is also in the 3-for-$5 Friday section, an easy add-on if you're already doing the Cheez-It/Post cereal deal.",
    "subtitle": "Lucerne cheese is also in the 3-for-$5 Friday section, an easy add-on if you're already doing the Cheez-It/Post cereal deal.",
    "badge": "FRIDAY",
    "price": "3 for $5",
    "availability": "Friday-only",
    "fridayOnly": true,
    "displayOrder": 3
  },
  {
    "title": "Ritz / Wheat Thins / Triscuit",
    "trackerFamilyIds": [
      "ritz_crackers",
      "nabisco_snack_crackers"
    ],
    "reason": "Ritz is basically Costco pricing in a smaller box. Costco is technically about 4% cheaper per ounce, but Vons lets you mix Ritz, Wheat Thins, and Triscuit instead of buying one giant box.",
    "subtitle": "Ritz is basically Costco pricing in a smaller box. Costco is technically about 4% cheaper per ounce, but Vons lets you mix Ritz, Wheat Thins, and Triscuit instead of buying one giant box.",
    "badge": "SNACKS",
    "price": "$2.49 each (buy 4+)",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 4
  },
  {
    "title": "Blueberries",
    "trackerFamilyIds": [
      "berries_6oz"
    ],
    "reason": "Blueberries are one of the clearest Costco-beaters: 18 oz would cost about $2.97 at Vons vs $5.99 at Costco.",
    "subtitle": "Blueberries are one of the clearest Costco-beaters: 18 oz would cost about $2.97 at Vons vs $5.99 at Costco.",
    "badge": "PRODUCE",
    "price": "$0.99 (6 oz, limit 6)",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 5
  },
  {
    "title": "Tuscan cantaloupe / watermelon",
    "trackerFamilyIds": [],
    "reason": "Tuscan cantaloupe is another half-price Costco comparison: Costco is about $4 each, Vons is $1.99.",
    "subtitle": "Tuscan cantaloupe is another half-price Costco comparison: Costco is about $4 each, Vons is $1.99.",
    "badge": "PRODUCE",
    "price": "$1.99 each",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 6
  },
  {
    "title": "Chobani 20g protein yogurt",
    "trackerFamilyIds": [
      "chobani_yogurt_per_cup"
    ],
    "reason": "Chobani 20g protein is $1 per cup at Vons this week. A 16-count equivalent is about $15.96 at Vons vs $18.99 at Costco.",
    "subtitle": "Chobani 20g protein is $1 per cup at Vons this week. A 16-count equivalent is about $15.96 at Vons vs $18.99 at Costco.",
    "badge": "DEAL",
    "price": "$3.99/4-pack (buy 4+)",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 7
  },
  {
    "title": "Doritos",
    "trackerFamilyIds": [
      "doritos_5_13oz"
    ],
    "reason": "Doritos are close to Costco pricing depending on the bag size, but Vons wins on variety because you can mix flavors instead of buying one huge Nacho Cheese bag.",
    "subtitle": "Doritos are close to Costco pricing depending on the bag size, but Vons wins on variety because you can mix flavors instead of buying one huge Nacho Cheese bag.",
    "badge": "SNACKS",
    "price": "2 for $5",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 8
  },
  {
    "title": "Nature Valley crunchy bars",
    "trackerFamilyIds": [
      "nature_valley_bars"
    ],
    "reason": "Best stack: buy five Nature Valley 12-count boxes, drop the total to $15, and get 60 pouches. Costco gives you 49 for about the same price.",
    "subtitle": "Best stack: buy five Nature Valley 12-count boxes, drop the total to $15, and get 60 pouches. Costco gives you 49 for about the same price.",
    "badge": "DEAL",
    "price": "$4/box \u2192 $3 after stack",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 9
  },
  {
    "title": "Cinnamon Toast Crunch",
    "trackerFamilyIds": [
      "general_mills_cereal_family_size"
    ],
    "reason": "Cinnamon Toast Crunch also works with the stack: five boxes drops to $15 total, about $0.16/oz, slightly cheaper than Costco.",
    "subtitle": "Cinnamon Toast Crunch also works with the stack: five boxes drops to $15 total, about $0.16/oz, slightly cheaper than Costco.",
    "badge": "DEAL",
    "price": "$4/box \u2192 $15 for 5",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 10
  },
  {
    "title": "Nature Valley protein bars",
    "trackerFamilyIds": [
      "nature_valley_bars"
    ],
    "reason": "Even Nature Valley Protein is not a Costco-beater, but it's close enough that if you want the Vons flavors and hit the stack, it's still a solid price.",
    "subtitle": "Even Nature Valley Protein is not a Costco-beater, but it's close enough that if you want the Vons flavors and hit the stack, it's still a solid price.",
    "badge": "DEAL",
    "price": "$4/box \u2192 $15 for 5",
    "availability": "",
    "fridayOnly": false,
    "displayOrder": 11
  }
],
};
