// AUTO-GENERATED by scripts/backfill_price_comparisons.py — do not edit by hand.
// Costco source: /Users/evelynchan/Documents/costco-mvp/costco_data

import type { CostcoRegion } from "./costcoRegions";

export type CostcoPricePoint = {
  date: string;
  region: CostcoRegion;
  price: number;
  unitPrice: number | null;
  packageDescription: string;
  availability: string | null;
  sourceFile: string;
};

/** Regional Costco price history keyed by canonical product id, then region slug. */
export const COSTCO_PRICE_HISTORY: Record<
  string,
  Partial<Record<CostcoRegion, CostcoPricePoint[]>>
> = {
  "strawberries": {
    "san-francisco": [
      {
        "date": "2026-06-19",
        "region": "san-francisco",
        "price": 11.99,
        "unitPrice": 2.9975,
        "packageDescription": "KIRKLAND SIGNATURE ORGANIC STRAWBERRIES 4 POUNDS",
        "availability": "in stock",
        "sourceFile": "2026-06-18_san-francisco_consolidated.csv"
      }
    ],
    "tustin": [
      {
        "date": "2026-06-19",
        "region": "tustin",
        "price": 11.69,
        "unitPrice": 2.9225,
        "packageDescription": "KIRKLAND SIGNATURE ORGANIC STRAWBERRIES 4 LBS",
        "availability": "in stock",
        "sourceFile": "2026-06-18_tustin_consolidated.csv"
      }
    ],
    "seattle": [
      {
        "date": "2026-03-30",
        "region": "seattle",
        "price": 8.99,
        "unitPrice": 1.2752,
        "packageDescription": "DJ&A FREEZE DRIED BANANA MANGO STRAWBERRY 7.05 OZ",
        "availability": "in stock",
        "sourceFile": "2026-03-30_seattle_consolidated.csv"
      },
      {
        "date": "2026-03-31",
        "region": "seattle",
        "price": 8.99,
        "unitPrice": 1.2752,
        "packageDescription": "DJ&A FREEZE DRIED BANANA MANGO STRAWBERRY 7.05 OZ",
        "availability": "in stock",
        "sourceFile": "2026-03-31_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-02",
        "region": "seattle",
        "price": 8.99,
        "unitPrice": 1.2752,
        "packageDescription": "DJ&A FREEZE DRIED BANANA MANGO STRAWBERRY 7.05 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-01_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-03",
        "region": "seattle",
        "price": 8.99,
        "unitPrice": 1.2752,
        "packageDescription": "DJ&A FREEZE DRIED BANANA MANGO STRAWBERRY 7.05 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-02_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-04",
        "region": "seattle",
        "price": 8.99,
        "unitPrice": 1.2752,
        "packageDescription": "DJ&A FREEZE DRIED BANANA MANGO STRAWBERRY 7.05 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-03_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-05",
        "region": "seattle",
        "price": 8.99,
        "unitPrice": 1.2752,
        "packageDescription": "DJ&A FREEZE DRIED BANANA MANGO STRAWBERRY 7.05 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-05_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-07",
        "region": "seattle",
        "price": 8.99,
        "unitPrice": 1.2752,
        "packageDescription": "DJ&A FREEZE DRIED BANANA MANGO STRAWBERRY 7.05 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-06_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-12",
        "region": "seattle",
        "price": 8.99,
        "unitPrice": 1.2752,
        "packageDescription": "DJ&A FREEZE DRIED BANANA MANGO STRAWBERRY 7.05 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-12_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-16",
        "region": "seattle",
        "price": 8.99,
        "unitPrice": 1.2752,
        "packageDescription": "DJ&A FREEZE DRIED BANANA MANGO STRAWBERRY 7.05 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-15_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-22",
        "region": "seattle",
        "price": 8.99,
        "unitPrice": 1.2752,
        "packageDescription": "DJ&A FREEZE DRIED BANANA MANGO STRAWBERRY 7.05 OZ",
        "availability": "low stock",
        "sourceFile": "2026-04-21_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-26",
        "region": "seattle",
        "price": 8.99,
        "unitPrice": 1.2752,
        "packageDescription": "DJ&A FREEZE DRIED BANANA MANGO STRAWBERRY 7.05 OZ",
        "availability": "low stock",
        "sourceFile": "2026-04-25_seattle_consolidated.csv"
      },
      {
        "date": "2026-06-19",
        "region": "seattle",
        "price": 11.39,
        "unitPrice": 2.8475,
        "packageDescription": "KIRKLAND SIGNATURE ORGANIC STRAWBERRIES 4 LB",
        "availability": "in stock",
        "sourceFile": "2026-06-18_seattle_consolidated.csv"
      }
    ]
  },
  "avocados": {},
  "doritos_nacho_cheese": {
    "san-francisco": [
      {
        "date": "2026-03-30",
        "region": "san-francisco",
        "price": 6.99,
        "unitPrice": 0.233,
        "packageDescription": "DORITOS NACHO CHEESE NKD 30 OZ",
        "availability": "in stock",
        "sourceFile": "2026-03-30_san-francisco_chips.csv"
      },
      {
        "date": "2026-06-19",
        "region": "san-francisco",
        "price": 6.99,
        "unitPrice": 0.233,
        "packageDescription": "DORITOS NACHO CHEESE 30 OUNCES",
        "availability": "in stock",
        "sourceFile": "2026-06-18_san-francisco_consolidated.csv"
      }
    ],
    "tustin": [
      {
        "date": "2026-03-30",
        "region": "tustin",
        "price": 7.29,
        "unitPrice": 0.243,
        "packageDescription": "FRITO LAY DORITOS 30 OZ",
        "availability": "in stock",
        "sourceFile": "2026-03-30_tustin_chips.csv"
      }
    ],
    "seattle": [
      {
        "date": "2026-03-30",
        "region": "seattle",
        "price": 7.29,
        "unitPrice": 0.243,
        "packageDescription": "DORITOS NACHO CHEESE 30 OZ",
        "availability": "in stock",
        "sourceFile": "2026-03-30_seattle_chips.csv"
      },
      {
        "date": "2026-06-19",
        "region": "seattle",
        "price": 7.29,
        "unitPrice": 0.243,
        "packageDescription": "DORITOS NACHO CHEESE 30 OZ",
        "availability": "in stock",
        "sourceFile": "2026-06-18_seattle_consolidated.csv"
      }
    ]
  },
  "cheetos_crunchy": {
    "san-francisco": [
      {
        "date": "2026-03-30",
        "region": "san-francisco",
        "price": 7.39,
        "unitPrice": 0.2639,
        "packageDescription": "FRITO LAY CHEETOS CRUNCHY 28 OUNCES",
        "availability": "low stock",
        "sourceFile": "2026-03-30_san-francisco_chips.csv"
      }
    ],
    "tustin": [
      {
        "date": "2026-03-30",
        "region": "tustin",
        "price": 7.39,
        "unitPrice": 0.2566,
        "packageDescription": "FRITO LAY CHEETOS FLAMIN HOT 28.8 OZ",
        "availability": "in stock",
        "sourceFile": "2026-03-30_tustin_chips.csv"
      }
    ],
    "seattle": [
      {
        "date": "2026-03-30",
        "region": "seattle",
        "price": 7.39,
        "unitPrice": 0.2566,
        "packageDescription": "CHEETOS CRUNCHY 28.8 OZ",
        "availability": "in stock",
        "sourceFile": "2026-03-30_seattle_chips.csv"
      }
    ]
  },
  "coke_zero": {},
  "chobani_greek_yogurt": {
    "san-francisco": [
      {
        "date": "2026-03-30",
        "region": "san-francisco",
        "price": 17.99,
        "unitPrice": 1.1244,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16 COUNT 6.7 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-03-30_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-03-31",
        "region": "san-francisco",
        "price": 17.99,
        "unitPrice": 1.1244,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16 COUNT 6.7 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-03-31_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-02",
        "region": "san-francisco",
        "price": 17.99,
        "unitPrice": 1.1244,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16 COUNT 6.7 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-04-01_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-03",
        "region": "san-francisco",
        "price": 17.99,
        "unitPrice": 1.1244,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16 COUNT 6.7 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-04-02_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-04",
        "region": "san-francisco",
        "price": 17.99,
        "unitPrice": 1.1244,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16 COUNT 6.7 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-04-03_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-05",
        "region": "san-francisco",
        "price": 17.99,
        "unitPrice": 1.1244,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16 COUNT 6.7 OUNCES EA",
        "availability": "low stock",
        "sourceFile": "2026-04-05_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-07",
        "region": "san-francisco",
        "price": 17.99,
        "unitPrice": 1.1244,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16 COUNT 6.7 OUNCES EA",
        "availability": "low stock",
        "sourceFile": "2026-04-06_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-12",
        "region": "san-francisco",
        "price": 18.99,
        "unitPrice": 1.1869,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16 COUNT 6.7 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-04-12_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-16",
        "region": "san-francisco",
        "price": 18.99,
        "unitPrice": 1.1869,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16 COUNT 6.7 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-04-15_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-22",
        "region": "san-francisco",
        "price": 18.99,
        "unitPrice": 1.1869,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16 COUNT 6.7 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-04-21_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-26",
        "region": "san-francisco",
        "price": 18.99,
        "unitPrice": 1.1869,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16 COUNT 6.7 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-04-25_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-05-03",
        "region": "san-francisco",
        "price": 18.99,
        "unitPrice": 1.1869,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16 COUNT 6.7 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-05-03_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-05-24",
        "region": "san-francisco",
        "price": 6.79,
        "unitPrice": 0.1698,
        "packageDescription": "CHOBANI 20G PROTEIN PLAIN GREEK YOGURT 40 OZ",
        "availability": "in stock",
        "sourceFile": "2026-05-24_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-06-04",
        "region": "san-francisco",
        "price": 6.79,
        "unitPrice": 0.1698,
        "packageDescription": "CHOBANI 20G PROTEIN PLAIN GREEK YOGURT 40 OUNCES",
        "availability": "in stock",
        "sourceFile": "2026-06-03_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-06-11",
        "region": "san-francisco",
        "price": 6.79,
        "unitPrice": 0.1698,
        "packageDescription": "CHOBANI 20G PROTEIN PLAIN GREEK YOGURT 40 OUNCES",
        "availability": "in stock",
        "sourceFile": "2026-06-11_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-06-19",
        "region": "san-francisco",
        "price": 6.79,
        "unitPrice": 0.1698,
        "packageDescription": "CHOBANI 20G PROTEIN PLAIN GREEK YOGURT 40 OUNCES",
        "availability": "in stock",
        "sourceFile": "2026-06-18_san-francisco_consolidated.csv"
      }
    ],
    "tustin": [
      {
        "date": "2026-03-30",
        "region": "tustin",
        "price": 17.99,
        "unitPrice": 0.1678,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16/6.7 OZ",
        "availability": "in stock",
        "sourceFile": "2026-03-30_tustin_consolidated.csv"
      },
      {
        "date": "2026-03-31",
        "region": "tustin",
        "price": 17.99,
        "unitPrice": 0.1678,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16/6.7 OZ",
        "availability": "in stock",
        "sourceFile": "2026-03-31_tustin_consolidated.csv"
      },
      {
        "date": "2026-04-02",
        "region": "tustin",
        "price": 17.99,
        "unitPrice": 0.1678,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16/6.7 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-01_tustin_consolidated.csv"
      },
      {
        "date": "2026-04-03",
        "region": "tustin",
        "price": 17.99,
        "unitPrice": 0.1678,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16/6.7 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-02_tustin_consolidated.csv"
      },
      {
        "date": "2026-04-04",
        "region": "tustin",
        "price": 17.99,
        "unitPrice": 0.1678,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16/6.7 OZ",
        "availability": "low stock",
        "sourceFile": "2026-04-03_tustin_consolidated.csv"
      },
      {
        "date": "2026-04-12",
        "region": "tustin",
        "price": 18.99,
        "unitPrice": 0.1771,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16/6.7 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-12_tustin_consolidated.csv"
      },
      {
        "date": "2026-04-16",
        "region": "tustin",
        "price": 18.99,
        "unitPrice": 0.1771,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16/6.7 OZ",
        "availability": "low stock",
        "sourceFile": "2026-04-15_tustin_consolidated.csv"
      },
      {
        "date": "2026-04-22",
        "region": "tustin",
        "price": 18.99,
        "unitPrice": 0.1771,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16/6.7 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-21_tustin_consolidated.csv"
      },
      {
        "date": "2026-04-26",
        "region": "tustin",
        "price": 18.99,
        "unitPrice": 0.1771,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16/6.7 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-25_tustin_consolidated.csv"
      },
      {
        "date": "2026-05-03",
        "region": "tustin",
        "price": 18.99,
        "unitPrice": 0.1771,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16/6.7 OZ",
        "availability": "in stock",
        "sourceFile": "2026-05-03_tustin_consolidated.csv"
      },
      {
        "date": "2026-05-24",
        "region": "tustin",
        "price": 18.99,
        "unitPrice": 0.1771,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16/6.7 OZ",
        "availability": "in stock",
        "sourceFile": "2026-05-24_tustin_consolidated.csv"
      },
      {
        "date": "2026-06-04",
        "region": "tustin",
        "price": 18.99,
        "unitPrice": 0.1771,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16/6.7 OZ",
        "availability": "in stock",
        "sourceFile": "2026-06-03_tustin_consolidated.csv"
      },
      {
        "date": "2026-06-11",
        "region": "tustin",
        "price": 18.99,
        "unitPrice": 0.1771,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16/6.7 OZ",
        "availability": "in stock",
        "sourceFile": "2026-06-11_tustin_consolidated.csv"
      },
      {
        "date": "2026-06-19",
        "region": "tustin",
        "price": 18.99,
        "unitPrice": 0.1771,
        "packageDescription": "CHOBANI 20G PROTEIN YOGURT 16/6.7 OZ",
        "availability": "in stock",
        "sourceFile": "2026-06-18_tustin_consolidated.csv"
      }
    ],
    "seattle": [
      {
        "date": "2026-06-19",
        "region": "seattle",
        "price": 17.89,
        "unitPrice": 0.1688,
        "packageDescription": "CHOBANI NON-FAT GREEK YOGURT 20/5.3 OZ",
        "availability": "in stock",
        "sourceFile": "2026-06-18_seattle_consolidated.csv"
      }
    ]
  },
  "cheerios": {
    "san-francisco": [
      {
        "date": "2026-03-30",
        "region": "san-francisco",
        "price": 6.99,
        "unitPrice": 0.1717,
        "packageDescription": "GENERAL MILLS CHEERIOS 2 PACK 20.35 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-03-30_san-francisco_cereal.csv"
      },
      {
        "date": "2026-06-19",
        "region": "san-francisco",
        "price": 4.99,
        "unitPrice": 0.1226,
        "packageDescription": "GENERAL MILLS CHEERIOS 2 PACK 20.35 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-06-18_san-francisco_consolidated.csv"
      }
    ],
    "tustin": [
      {
        "date": "2026-03-30",
        "region": "tustin",
        "price": 6.99,
        "unitPrice": 0.1717,
        "packageDescription": "GENERAL MILLS CHEERIOS 40.7 OZ",
        "availability": "in stock",
        "sourceFile": "2026-03-30_tustin_cereal.csv"
      },
      {
        "date": "2026-06-19",
        "region": "tustin",
        "price": 4.99,
        "unitPrice": 0.1226,
        "packageDescription": "GENERAL MILLS CHEERIOS 40.7 OZ (2LB 8.7OZ)",
        "availability": "in stock",
        "sourceFile": "2026-06-18_tustin_consolidated.csv"
      }
    ],
    "seattle": [
      {
        "date": "2026-03-30",
        "region": "seattle",
        "price": 6.99,
        "unitPrice": 0.1722,
        "packageDescription": "GENERAL MILLS CHEERIOS 2/20.3 OZ",
        "availability": "in stock",
        "sourceFile": "2026-03-30_seattle_cereal.csv"
      },
      {
        "date": "2026-06-19",
        "region": "seattle",
        "price": 4.99,
        "unitPrice": 0.1229,
        "packageDescription": "GENERAL MILLS CHEERIOS 2/20.3 OZ",
        "availability": "in stock",
        "sourceFile": "2026-06-18_seattle_consolidated.csv"
      }
    ]
  },
  "tillamook_ice_cream": {},
  "mission_tortilla_chips": {},
  "nature_valley_bars": {
    "san-francisco": [
      {
        "date": "2026-04-04",
        "region": "san-francisco",
        "price": 14.99,
        "unitPrice": 0.3059,
        "packageDescription": "NATURE VALLEY OATS 'N HONEY BAR 49 BARS 1.5 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-04-03_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-05",
        "region": "san-francisco",
        "price": 14.99,
        "unitPrice": 0.3059,
        "packageDescription": "NATURE VALLEY OATS 'N HONEY BAR 49 BARS 1.5 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-04-05_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-07",
        "region": "san-francisco",
        "price": 10.99,
        "unitPrice": 0.2243,
        "packageDescription": "NATURE VALLEY OATS 'N HONEY BAR 49 BARS 1.5 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-04-06_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-12",
        "region": "san-francisco",
        "price": 10.99,
        "unitPrice": 0.2243,
        "packageDescription": "NATURE VALLEY OATS 'N HONEY BAR 49 BARS 1.5 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-04-12_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-16",
        "region": "san-francisco",
        "price": 10.99,
        "unitPrice": 0.2243,
        "packageDescription": "NATURE VALLEY OATS 'N HONEY BAR 49 BARS 1.5 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-04-15_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-22",
        "region": "san-francisco",
        "price": 10.99,
        "unitPrice": 0.2243,
        "packageDescription": "NATURE VALLEY OATS 'N HONEY BAR 49 BARS 1.5 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-04-21_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-26",
        "region": "san-francisco",
        "price": 10.99,
        "unitPrice": 0.2243,
        "packageDescription": "NATURE VALLEY OATS 'N HONEY BAR 49 BARS 1.5 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-04-25_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-05-03",
        "region": "san-francisco",
        "price": 10.99,
        "unitPrice": 0.2243,
        "packageDescription": "NATURE VALLEY OATS 'N HONEY BAR 49 BARS 1.5 OUNCES EA",
        "availability": "low stock",
        "sourceFile": "2026-05-03_san-francisco_consolidated.csv"
      }
    ],
    "seattle": [
      {
        "date": "2026-03-30",
        "region": "seattle",
        "price": 14.99,
        "unitPrice": 0.2053,
        "packageDescription": "NATURE VALLEY CRUNCHY GRANOLA BAR 49/1.49 OZ",
        "availability": "in stock",
        "sourceFile": "2026-03-30_seattle_consolidated.csv"
      },
      {
        "date": "2026-03-31",
        "region": "seattle",
        "price": 14.99,
        "unitPrice": 0.2053,
        "packageDescription": "NATURE VALLEY CRUNCHY GRANOLA BAR 49/1.49 OZ",
        "availability": "in stock",
        "sourceFile": "2026-03-31_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-02",
        "region": "seattle",
        "price": 14.99,
        "unitPrice": 0.2053,
        "packageDescription": "NATURE VALLEY CRUNCHY GRANOLA BAR 49/1.49 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-01_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-03",
        "region": "seattle",
        "price": 14.99,
        "unitPrice": 0.2053,
        "packageDescription": "NATURE VALLEY CRUNCHY GRANOLA BAR 49/1.49 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-02_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-04",
        "region": "seattle",
        "price": 14.99,
        "unitPrice": 0.2053,
        "packageDescription": "NATURE VALLEY CRUNCHY GRANOLA BAR 49/1.49 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-03_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-05",
        "region": "seattle",
        "price": 14.99,
        "unitPrice": 0.2053,
        "packageDescription": "NATURE VALLEY CRUNCHY GRANOLA BAR 49/1.49 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-05_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-07",
        "region": "seattle",
        "price": 10.99,
        "unitPrice": 0.1505,
        "packageDescription": "NATURE VALLEY CRUNCHY GRANOLA BAR 49/1.49 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-06_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-12",
        "region": "seattle",
        "price": 10.99,
        "unitPrice": 0.1505,
        "packageDescription": "NATURE VALLEY CRUNCHY GRANOLA BAR 49/1.49 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-12_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-16",
        "region": "seattle",
        "price": 10.99,
        "unitPrice": 0.1505,
        "packageDescription": "NATURE VALLEY CRUNCHY GRANOLA BAR 49/1.49 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-15_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-22",
        "region": "seattle",
        "price": 10.99,
        "unitPrice": 0.1505,
        "packageDescription": "NATURE VALLEY CRUNCHY GRANOLA BAR 49/1.49 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-21_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-26",
        "region": "seattle",
        "price": 10.99,
        "unitPrice": 0.1505,
        "packageDescription": "NATURE VALLEY CRUNCHY GRANOLA BAR 49/1.49 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-25_seattle_consolidated.csv"
      },
      {
        "date": "2026-05-03",
        "region": "seattle",
        "price": 10.99,
        "unitPrice": 0.1505,
        "packageDescription": "NATURE VALLEY CRUNCHY GRANOLA BAR 49/1.49 OZ",
        "availability": "in stock",
        "sourceFile": "2026-05-03_seattle_consolidated.csv"
      },
      {
        "date": "2026-06-19",
        "region": "seattle",
        "price": 14.99,
        "unitPrice": 0.2053,
        "packageDescription": "NATURE VALLEY CRUNCHY GRANOLA BAR 49/1.49 OZ",
        "availability": "in stock",
        "sourceFile": "2026-06-18_seattle_consolidated.csv"
      }
    ]
  },
  "fage_greek_yogurt": {
    "san-francisco": [
      {
        "date": "2026-06-19",
        "region": "san-francisco",
        "price": 7.79,
        "unitPrice": 0.1623,
        "packageDescription": "FAGE TOTAL GREEK NONFAT YOGURT 48 OUNCES",
        "availability": "in stock",
        "sourceFile": "2026-06-18_san-francisco_consolidated.csv"
      }
    ],
    "tustin": [
      {
        "date": "2026-06-19",
        "region": "tustin",
        "price": 7.69,
        "unitPrice": 0.1602,
        "packageDescription": "FAGE TOTAL GREEK NONFAT YOGURT 48 OZ",
        "availability": "low stock",
        "sourceFile": "2026-06-18_tustin_consolidated.csv"
      }
    ]
  },
  "frito_lay_multipack_chips": {
    "san-francisco": [
      {
        "date": "2026-03-30",
        "region": "san-francisco",
        "price": 19.49,
        "unitPrice": 0.6497,
        "packageDescription": "FRITO LAY SUNCHIPS VARIETY 30 COUNT 1.5 OUNCES EA",
        "availability": "low stock",
        "sourceFile": "2026-03-30_san-francisco_chips.csv"
      }
    ],
    "tustin": [
      {
        "date": "2026-03-30",
        "region": "tustin",
        "price": 19.49,
        "unitPrice": 0.6497,
        "packageDescription": "FRITO LAY SELECT MIX VARIETY 30 CT/ 47.0 OZ",
        "availability": "in stock",
        "sourceFile": "2026-03-30_tustin_chips.csv"
      }
    ],
    "seattle": [
      {
        "date": "2026-03-30",
        "region": "seattle",
        "price": 19.49,
        "unitPrice": 0.6497,
        "packageDescription": "FRITO LAY VARIETY 30 CT",
        "availability": "in stock",
        "sourceFile": "2026-03-30_seattle_chips.csv"
      }
    ]
  },
  "haagen_dazs_ice_cream": {},
  "grapes": {
    "san-francisco": [
      {
        "date": "2026-06-19",
        "region": "san-francisco",
        "price": 9.99,
        "unitPrice": 3.33,
        "packageDescription": "ORGANIC COTTON CANDY GRAPES 3 LBS",
        "availability": "in stock",
        "sourceFile": "2026-06-18_san-francisco_consolidated.csv"
      }
    ],
    "tustin": [
      {
        "date": "2026-06-19",
        "region": "tustin",
        "price": 11.99,
        "unitPrice": 3.9967,
        "packageDescription": "ORGANIC COTTON CANDY GRAPES 3 LBS",
        "availability": "in stock",
        "sourceFile": "2026-06-18_tustin_consolidated.csv"
      }
    ],
    "seattle": [
      {
        "date": "2026-06-19",
        "region": "seattle",
        "price": 11.99,
        "unitPrice": 3.9967,
        "packageDescription": "ORGANIC COTTON CANDY GRAPES 3 LBS",
        "availability": "in stock",
        "sourceFile": "2026-06-18_seattle_consolidated.csv"
      }
    ]
  },
  "eggs_18_count": {
    "san-francisco": [
      {
        "date": "2026-06-19",
        "region": "san-francisco",
        "price": 5.29,
        "unitPrice": 5.29,
        "packageDescription": "KIRKLAND SIGNATURE CAGE FREE LARGE EGGS GRADE AA USDA 2 DOZEN",
        "availability": "in stock",
        "sourceFile": "2026-06-18_san-francisco_consolidated.csv"
      }
    ],
    "tustin": [
      {
        "date": "2026-06-19",
        "region": "tustin",
        "price": 3.49,
        "unitPrice": 0.1454,
        "packageDescription": "KIRKLAND SIGNATURE CAGE FREE LARGE EGGS USDA GRADE AA 24 CT",
        "availability": "in stock",
        "sourceFile": "2026-06-18_tustin_consolidated.csv"
      }
    ],
    "seattle": [
      {
        "date": "2026-06-19",
        "region": "seattle",
        "price": 5.59,
        "unitPrice": 5.59,
        "packageDescription": "KIRKLAND SIGNATURE USDA GRADE AA CAGE FREE LRG EGGS 2DZ",
        "availability": "in stock",
        "sourceFile": "2026-06-18_seattle_consolidated.csv"
      }
    ]
  },
  "oreos_sandwich_cookies": {
    "tustin": [
      {
        "date": "2026-06-19",
        "region": "tustin",
        "price": 12.39,
        "unitPrice": 0.1974,
        "packageDescription": "NABISCO OREO COOKIES 62.76 OZ",
        "availability": "in stock",
        "sourceFile": "2026-06-18_tustin_consolidated.csv"
      }
    ],
    "seattle": [
      {
        "date": "2026-06-19",
        "region": "seattle",
        "price": 10.99,
        "unitPrice": 0.1751,
        "packageDescription": "NABISCO OREO COOKIES 62.76 OZ",
        "availability": "in stock",
        "sourceFile": "2026-06-18_seattle_consolidated.csv"
      }
    ]
  },
  "protein_bars": {
    "san-francisco": [
      {
        "date": "2026-03-30",
        "region": "san-francisco",
        "price": 19.99,
        "unitPrice": 0.7139,
        "packageDescription": "RXBAR PROTEIN BITES STRAWBERRY PEANUT BUTTER 28 COUNT",
        "availability": "in stock",
        "sourceFile": "2026-03-30_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-03-31",
        "region": "san-francisco",
        "price": 19.99,
        "unitPrice": 0.7139,
        "packageDescription": "RXBAR PROTEIN BITES STRAWBERRY PEANUT BUTTER 28 COUNT",
        "availability": "in stock",
        "sourceFile": "2026-03-31_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-02",
        "region": "san-francisco",
        "price": 19.99,
        "unitPrice": 0.7139,
        "packageDescription": "RXBAR PROTEIN BITES STRAWBERRY PEANUT BUTTER 28 COUNT",
        "availability": "in stock",
        "sourceFile": "2026-04-01_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-03",
        "region": "san-francisco",
        "price": 19.99,
        "unitPrice": 0.7139,
        "packageDescription": "RXBAR PROTEIN BITES STRAWBERRY PEANUT BUTTER 28 COUNT",
        "availability": "in stock",
        "sourceFile": "2026-04-02_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-04",
        "region": "san-francisco",
        "price": 19.99,
        "unitPrice": 0.7139,
        "packageDescription": "RXBAR PROTEIN BITES STRAWBERRY PEANUT BUTTER 28 COUNT",
        "availability": "in stock",
        "sourceFile": "2026-04-03_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-05",
        "region": "san-francisco",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-05_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-07",
        "region": "san-francisco",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-06_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-12",
        "region": "san-francisco",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-12_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-16",
        "region": "san-francisco",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-15_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-22",
        "region": "san-francisco",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-21_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-26",
        "region": "san-francisco",
        "price": 17.99,
        "unitPrice": 0.7496,
        "packageDescription": "ZBAR PROTEIN BARS VARIETY PACK 24 BARS 1.27 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-04-25_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-05-03",
        "region": "san-francisco",
        "price": 17.99,
        "unitPrice": 0.7496,
        "packageDescription": "ZBAR PROTEIN BARS VARIETY PACK 24 BARS 1.27 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-05-03_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-05-24",
        "region": "san-francisco",
        "price": 24.99,
        "unitPrice": 2.0825,
        "packageDescription": "DAVID PROTEIN BAR VARIETY 12 BARS 2.19 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-05-24_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-06-04",
        "region": "san-francisco",
        "price": 24.99,
        "unitPrice": 2.0825,
        "packageDescription": "DAVID PROTEIN BAR VARIETY 12 BARS 2.19 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-06-03_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-06-11",
        "region": "san-francisco",
        "price": 24.99,
        "unitPrice": 2.0825,
        "packageDescription": "DAVID PROTEIN BAR VARIETY 12 BARS 2.19 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-06-11_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-06-19",
        "region": "san-francisco",
        "price": 24.99,
        "unitPrice": 2.0825,
        "packageDescription": "DAVID PROTEIN BAR VARIETY 12 BARS 2.19 OUNCES EA",
        "availability": "in stock",
        "sourceFile": "2026-06-18_san-francisco_consolidated.csv"
      }
    ],
    "tustin": [
      {
        "date": "2026-03-30",
        "region": "tustin",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "in stock",
        "sourceFile": "2026-03-30_tustin_consolidated.csv"
      },
      {
        "date": "2026-03-31",
        "region": "tustin",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "in stock",
        "sourceFile": "2026-03-31_tustin_consolidated.csv"
      },
      {
        "date": "2026-04-02",
        "region": "tustin",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-01_tustin_consolidated.csv"
      },
      {
        "date": "2026-04-03",
        "region": "tustin",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-02_tustin_consolidated.csv"
      },
      {
        "date": "2026-04-04",
        "region": "tustin",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-03_tustin_consolidated.csv"
      },
      {
        "date": "2026-04-05",
        "region": "tustin",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-05_tustin_consolidated.csv"
      },
      {
        "date": "2026-04-07",
        "region": "tustin",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-06_tustin_consolidated.csv"
      },
      {
        "date": "2026-04-12",
        "region": "tustin",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-12_tustin_consolidated.csv"
      },
      {
        "date": "2026-04-16",
        "region": "tustin",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-15_tustin_consolidated.csv"
      },
      {
        "date": "2026-04-22",
        "region": "tustin",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-21_tustin_consolidated.csv"
      },
      {
        "date": "2026-04-26",
        "region": "tustin",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-25_tustin_consolidated.csv"
      },
      {
        "date": "2026-05-03",
        "region": "tustin",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "in stock",
        "sourceFile": "2026-05-03_tustin_consolidated.csv"
      },
      {
        "date": "2026-05-24",
        "region": "tustin",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "in stock",
        "sourceFile": "2026-05-24_tustin_consolidated.csv"
      },
      {
        "date": "2026-06-04",
        "region": "tustin",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "in stock",
        "sourceFile": "2026-06-03_tustin_consolidated.csv"
      },
      {
        "date": "2026-06-11",
        "region": "tustin",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "in stock",
        "sourceFile": "2026-06-11_tustin_consolidated.csv"
      },
      {
        "date": "2026-06-19",
        "region": "tustin",
        "price": 26.99,
        "unitPrice": 0.7957,
        "packageDescription": "QUEST PROTEIN BAR CHOC CHIP / COOKIESNCR 16/2.12 OZ",
        "availability": "low stock",
        "sourceFile": "2026-06-18_tustin_consolidated.csv"
      }
    ],
    "seattle": [
      {
        "date": "2026-03-30",
        "region": "seattle",
        "price": 20.49,
        "unitPrice": 0.5395,
        "packageDescription": "THINK! PROTEIN BAR VARIETY 18/2.11 OZ",
        "availability": "in stock",
        "sourceFile": "2026-03-30_seattle_consolidated.csv"
      },
      {
        "date": "2026-03-31",
        "region": "seattle",
        "price": 20.49,
        "unitPrice": 0.5395,
        "packageDescription": "THINK! PROTEIN BAR VARIETY 18/2.11 OZ",
        "availability": "in stock",
        "sourceFile": "2026-03-31_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-02",
        "region": "seattle",
        "price": 20.49,
        "unitPrice": 0.5395,
        "packageDescription": "THINK! PROTEIN BAR VARIETY 18/2.11 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-01_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-03",
        "region": "seattle",
        "price": 20.49,
        "unitPrice": 0.5395,
        "packageDescription": "THINK! PROTEIN BAR VARIETY 18/2.11 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-02_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-04",
        "region": "seattle",
        "price": 20.49,
        "unitPrice": 0.5395,
        "packageDescription": "THINK! PROTEIN BAR VARIETY 18/2.11 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-03_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-05",
        "region": "seattle",
        "price": 20.49,
        "unitPrice": 0.5395,
        "packageDescription": "THINK! PROTEIN BAR VARIETY 18/2.11 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-05_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-07",
        "region": "seattle",
        "price": 20.49,
        "unitPrice": 0.5395,
        "packageDescription": "THINK! PROTEIN BAR VARIETY 18/2.11 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-06_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-12",
        "region": "seattle",
        "price": 20.49,
        "unitPrice": 0.5395,
        "packageDescription": "THINK! PROTEIN BAR VARIETY 18/2.11 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-12_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-16",
        "region": "seattle",
        "price": 20.49,
        "unitPrice": 0.5395,
        "packageDescription": "THINK! PROTEIN BAR VARIETY 18/2.11 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-15_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-22",
        "region": "seattle",
        "price": 20.49,
        "unitPrice": 0.5395,
        "packageDescription": "THINK! PROTEIN BAR VARIETY 18/2.11 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-21_seattle_consolidated.csv"
      },
      {
        "date": "2026-04-26",
        "region": "seattle",
        "price": 20.49,
        "unitPrice": 0.5395,
        "packageDescription": "THINK! PROTEIN BAR VARIETY 18/2.11 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-25_seattle_consolidated.csv"
      },
      {
        "date": "2026-05-03",
        "region": "seattle",
        "price": 20.49,
        "unitPrice": 0.5395,
        "packageDescription": "THINK! PROTEIN BAR VARIETY 18/2.11 OZ",
        "availability": "in stock",
        "sourceFile": "2026-05-03_seattle_consolidated.csv"
      },
      {
        "date": "2026-05-24",
        "region": "seattle",
        "price": 20.49,
        "unitPrice": 0.5395,
        "packageDescription": "THINK! PROTEIN BAR VARIETY 18/2.11 OZ",
        "availability": "in stock",
        "sourceFile": "2026-05-24_seattle_consolidated.csv"
      },
      {
        "date": "2026-06-04",
        "region": "seattle",
        "price": 20.49,
        "unitPrice": 0.5395,
        "packageDescription": "THINK! PROTEIN BAR VARIETY 18/2.11 OZ",
        "availability": "in stock",
        "sourceFile": "2026-06-03_seattle_consolidated.csv"
      },
      {
        "date": "2026-06-11",
        "region": "seattle",
        "price": 20.49,
        "unitPrice": 0.5395,
        "packageDescription": "THINK! PROTEIN BAR VARIETY 18/2.11 OZ",
        "availability": "in stock",
        "sourceFile": "2026-06-11_seattle_consolidated.csv"
      },
      {
        "date": "2026-06-19",
        "region": "seattle",
        "price": 20.49,
        "unitPrice": 0.5395,
        "packageDescription": "THINK! PROTEIN BAR VARIETY 18/2.11 OZ",
        "availability": "in stock",
        "sourceFile": "2026-06-18_seattle_consolidated.csv"
      }
    ]
  },
  "kettle_brand_chips": {
    "san-francisco": [
      {
        "date": "2026-04-16",
        "region": "san-francisco",
        "price": 6.59,
        "unitPrice": 0.2354,
        "packageDescription": "KETTLE POTATO CHIPS JALAPENO 28 OUNCES",
        "availability": "in stock",
        "sourceFile": "2026-04-15_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-22",
        "region": "san-francisco",
        "price": 6.69,
        "unitPrice": 0.2389,
        "packageDescription": "KETTLE POTATO CHIPS JALAPENO 28 OUNCES",
        "availability": "in stock",
        "sourceFile": "2026-04-21_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-04-26",
        "region": "san-francisco",
        "price": 6.69,
        "unitPrice": 0.2389,
        "packageDescription": "KETTLE POTATO CHIPS JALAPENO 28 OUNCES",
        "availability": "in stock",
        "sourceFile": "2026-04-25_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-05-03",
        "region": "san-francisco",
        "price": 6.69,
        "unitPrice": 0.2389,
        "packageDescription": "KETTLE POTATO CHIPS JALAPENO 28 OUNCES",
        "availability": "in stock",
        "sourceFile": "2026-05-03_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-05-24",
        "region": "san-francisco",
        "price": 6.69,
        "unitPrice": 0.2389,
        "packageDescription": "KETTLE POTATO CHIPS JALAPENO 28 OUNCES",
        "availability": "in stock",
        "sourceFile": "2026-05-24_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-06-04",
        "region": "san-francisco",
        "price": 6.69,
        "unitPrice": 0.2389,
        "packageDescription": "KETTLE POTATO CHIPS JALAPENO 28 OUNCES",
        "availability": "in stock",
        "sourceFile": "2026-06-03_san-francisco_consolidated.csv"
      },
      {
        "date": "2026-06-11",
        "region": "san-francisco",
        "price": 7.99,
        "unitPrice": 0.2663,
        "packageDescription": "CAPE COD KETTLE COOKED CHIPS 30 OUNCES",
        "availability": "in stock",
        "sourceFile": "2026-06-11_san-francisco_consolidated.csv"
      }
    ],
    "tustin": [
      {
        "date": "2026-04-22",
        "region": "tustin",
        "price": 6.69,
        "unitPrice": 0.2389,
        "packageDescription": "KETTLE BRAND JALAPENO POTATO CHIPS 28 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-21_tustin_consolidated.csv"
      },
      {
        "date": "2026-04-26",
        "region": "tustin",
        "price": 6.69,
        "unitPrice": 0.2389,
        "packageDescription": "KETTLE BRAND JALAPENO POTATO CHIPS 28 OZ",
        "availability": "in stock",
        "sourceFile": "2026-04-25_tustin_consolidated.csv"
      },
      {
        "date": "2026-05-03",
        "region": "tustin",
        "price": 6.69,
        "unitPrice": 0.2389,
        "packageDescription": "KETTLE BRAND JALAPENO POTATO CHIPS 28 OZ",
        "availability": "in stock",
        "sourceFile": "2026-05-03_tustin_consolidated.csv"
      },
      {
        "date": "2026-05-24",
        "region": "tustin",
        "price": 7.99,
        "unitPrice": 0.2663,
        "packageDescription": "CAPE COD KETTLE COOKED CHIPS 30 OZ",
        "availability": "in stock",
        "sourceFile": "2026-05-24_tustin_consolidated.csv"
      },
      {
        "date": "2026-06-04",
        "region": "tustin",
        "price": 7.99,
        "unitPrice": 0.2663,
        "packageDescription": "CAPE COD KETTLE COOKED CHIPS 30 OZ",
        "availability": "in stock",
        "sourceFile": "2026-06-03_tustin_consolidated.csv"
      },
      {
        "date": "2026-06-11",
        "region": "tustin",
        "price": 7.99,
        "unitPrice": 0.2663,
        "packageDescription": "CAPE COD KETTLE COOKED CHIPS 30 OZ",
        "availability": "in stock",
        "sourceFile": "2026-06-11_tustin_consolidated.csv"
      }
    ]
  }
};
