// AUTO-GENERATED by scripts/generate_weekly_ad_prices.py — do not edit by hand.
// Source manifest: data/weekly_ads/flyer_manifest_safeway.csv
// Source offers: scrolling-the-aisle/outputs/product_discovery_safeway/split_offer_items.csv

import type { GeneratedWeeklyAdPrice, WeeklyAdWeek } from "./weeklyAdPrices.generated";

export type { GeneratedWeeklyAdPrice, WeeklyAdWeek };

export const FAMILY_WEEKLY_AD_WEEKS: WeeklyAdWeek[] = [
  {
    "weekStart": "2026-03-25",
    "weekEnd": "2026-03-31",
    "sourceFile": "safeway 3-25 - 3-31.pdf",
    "sourceLabel": "Safeway weekly ad 03/25\u201303/31"
  },
  {
    "weekStart": "2026-04-01",
    "weekEnd": "2026-04-07",
    "sourceFile": "safeway 4-1 - 4-7.pdf",
    "sourceLabel": "Safeway weekly ad 04/01\u201304/07"
  },
  {
    "weekStart": "2026-05-06",
    "weekEnd": "2026-05-12",
    "sourceFile": "safeway 5-6 - 5-12.pdf",
    "sourceLabel": "Safeway weekly ad 05/06\u201305/12"
  },
  {
    "weekStart": "2026-05-12",
    "weekEnd": "2026-05-19",
    "sourceFile": "safeway 5-12 - 5-19.pdf",
    "sourceLabel": "Safeway weekly ad 05/12\u201305/19"
  },
  {
    "weekStart": "2026-06-03",
    "weekEnd": "2026-06-09",
    "sourceFile": "safeway 6-3 - 6-9.pdf",
    "sourceLabel": "Safeway weekly ad 06/03\u201306/09"
  },
  {
    "weekStart": "2026-06-10",
    "weekEnd": "2026-06-16",
    "sourceFile": "safeway 6-10 - 6-16.pdf",
    "sourceLabel": "Safeway weekly ad 06/10\u201306/16"
  },
  {
    "weekStart": "2026-06-17",
    "weekEnd": "2026-06-23",
    "sourceFile": "safeway 6-17 - 6-23.pdf",
    "sourceLabel": "Safeway weekly ad 06/17\u201306/23"
  },
  {
    "weekStart": "2026-06-24",
    "weekEnd": "2026-06-30",
    "sourceFile": "safeway 6-24 - 6-30.pdf",
    "sourceLabel": "Safeway weekly ad 06/24\u201306/30"
  },
  {
    "weekStart": "2026-07-01",
    "weekEnd": "2026-07-07",
    "sourceFile": "safeway 7-1 - 7-7.pdf",
    "sourceLabel": "Safeway weekly ad 07/01\u201307/07"
  }
];

export const FAMILY_WEEKLY_AD_PRICES: Record<
  string,
  Record<string, GeneratedWeeklyAdPrice>
> = {
  "ben_jerrys_ice_cream": {
    "2026-03-25": {
      "price": 3.49,
      "offerText": "Ben & Jerry\u2019s Ice Cream 16 oz",
      "confidence": "high"
    },
    "2026-04-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-12": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-24": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-07-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "ritz_crackers_snacks": {
    "2026-03-25": {
      "price": 2.49,
      "offerText": "Ritz Crackers 7.1 to 13.7 oz, Chips Ahoy! Cookies 7 to 13 oz",
      "confidence": "medium"
    },
    "2026-04-01": {
      "price": 2.49,
      "offerText": "Ritz Crackers",
      "confidence": "high"
    },
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-12": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": 2.49,
      "offerText": "Ritz Crackers",
      "confidence": "high"
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-24": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-07-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  }
};

export const FAMILY_MEMBER_WEEKLY_AD_PRICES: Record<
  string,
  Record<string, Record<string, GeneratedWeeklyAdPrice>>
> = {
  "ben_jerrys_ice_cream": {
    "pint": {
      "2026-03-25": {
        "price": 3.49,
        "offerText": "Ben & Jerry\u2019s Ice Cream 16 oz",
        "confidence": "high"
      },
      "2026-04-01": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-05-06": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-05-12": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-03": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-10": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-17": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-24": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-07-01": {
        "price": null,
        "offerText": null,
        "confidence": null
      }
    },
    "non_dairy_pint": {
      "2026-03-25": {
        "price": 3.49,
        "offerText": "Ben & Jerry\u2019s Ice Cream 16 oz",
        "confidence": "medium"
      },
      "2026-04-01": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-05-06": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-05-12": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-03": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-10": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-17": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-24": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-07-01": {
        "price": null,
        "offerText": null,
        "confidence": null
      }
    },
    "bars_4ct": {
      "2026-03-25": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-04-01": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-05-06": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-05-12": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-03": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-10": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-17": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-24": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-07-01": {
        "price": null,
        "offerText": null,
        "confidence": null
      }
    }
  },
  "ritz_crackers_snacks": {
    "classic_box": {
      "2026-03-25": {
        "price": 2.49,
        "offerText": "Ritz Crackers 7.1 to 13.7 oz, Chips Ahoy! Cookies 7 to 13 oz",
        "confidence": "medium"
      },
      "2026-04-01": {
        "price": 2.49,
        "offerText": "Ritz Crackers",
        "confidence": "high"
      },
      "2026-05-06": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-05-12": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-03": {
        "price": 2.49,
        "offerText": "Ritz Crackers",
        "confidence": "high"
      },
      "2026-06-10": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-17": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-24": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-07-01": {
        "price": null,
        "offerText": null,
        "confidence": null
      }
    }
  }
};

export const VONS_FAMILY_WEEKLY_AD_WEEKS: WeeklyAdWeek[] = [
  {
    "weekStart": "2026-05-06",
    "weekEnd": "2026-05-12",
    "sourceFile": "vons 5-6 - 5-12.pdf",
    "sourceLabel": "Vons weekly ad 05/06\u201305/12"
  },
  {
    "weekStart": "2026-05-13",
    "weekEnd": "2026-05-19",
    "sourceFile": "vons 5-13 - 5-19.pdf",
    "sourceLabel": "Vons weekly ad 05/13\u201305/19"
  },
  {
    "weekStart": "2026-05-20",
    "weekEnd": "2026-05-26",
    "sourceFile": "vons 5-20 - 5-26.pdf",
    "sourceLabel": "Vons weekly ad 05/20\u201305/26"
  },
  {
    "weekStart": "2026-06-03",
    "weekEnd": "2026-06-09",
    "sourceFile": "vons 6-3 - 6-9.pdf",
    "sourceLabel": "Vons weekly ad 06/03\u201306/09"
  },
  {
    "weekStart": "2026-06-10",
    "weekEnd": "2026-06-16",
    "sourceFile": "vons 6-10 - 6-16.pdf",
    "sourceLabel": "Vons weekly ad 06/10\u201306/16"
  },
  {
    "weekStart": "2026-06-17",
    "weekEnd": "2026-06-23",
    "sourceFile": "vons 6-17 - 6-23.pdf",
    "sourceLabel": "Vons weekly ad 06/17\u201306/23"
  },
  {
    "weekStart": "2026-06-24",
    "weekEnd": "2026-06-30",
    "sourceFile": "vons 6-24 - 6-30.pdf",
    "sourceLabel": "Vons weekly ad 06/24\u201306/30"
  },
  {
    "weekStart": "2026-07-01",
    "weekEnd": "2026-07-07",
    "sourceFile": "vons 7-1 - 7-7.pdf",
    "sourceLabel": "Vons weekly ad 07/01\u201307/07"
  }
];

export const VONS_FAMILY_WEEKLY_AD_PRICES: Record<
  string,
  Record<string, GeneratedWeeklyAdPrice>
> = {
  "ben_jerrys_ice_cream": {
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-13": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-20": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-24": {
      "price": 4.99,
      "offerText": "Ben & Jerry's Ice Cream or Non-Dairy 16 oz Selected varieties",
      "confidence": "medium"
    },
    "2026-07-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "ritz_crackers_snacks": {
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-13": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-20": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": 2.49,
      "offerText": "Ritz Crackers 5 to 13 oz",
      "confidence": "high"
    },
    "2026-06-24": {
      "price": 2.99,
      "offerText": "Nabisco Ritz Crackers",
      "confidence": "medium"
    },
    "2026-07-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  }
};

export const VONS_FAMILY_MEMBER_WEEKLY_AD_PRICES: Record<
  string,
  Record<string, Record<string, GeneratedWeeklyAdPrice>>
> = {
  "ben_jerrys_ice_cream": {
    "pint": {
      "2026-05-06": {
        "price": 3.99,
        "offerText": "Ben & Jerry\u2019s 14.4-16 oz. or 4 ct. Breyers 1.5 qt. Klondike 4-6 ct. or talenti 10.2-16 oz. Selected varieties",
        "confidence": "medium"
      },
      "2026-05-13": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-05-20": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-03": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-10": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-17": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-24": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-07-01": {
        "price": null,
        "offerText": null,
        "confidence": null
      }
    },
    "non_dairy_pint": {
      "2026-05-06": {
        "price": 3.99,
        "offerText": "Ben & Jerry\u2019s 14.4-16 oz. or 4 ct. Breyers 1.5 qt. Klondike 4-6 ct. or talenti 10.2-16 oz. Selected varieties",
        "confidence": "medium"
      },
      "2026-05-13": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-05-20": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-03": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-10": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-17": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-24": {
        "price": 4.99,
        "offerText": "Ben & Jerry's Ice Cream or Non-Dairy 16 oz Selected varieties",
        "confidence": "medium"
      },
      "2026-07-01": {
        "price": null,
        "offerText": null,
        "confidence": null
      }
    },
    "bars_4ct": {
      "2026-05-06": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-05-13": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-05-20": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-03": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-10": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-17": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-24": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-07-01": {
        "price": null,
        "offerText": null,
        "confidence": null
      }
    }
  },
  "ritz_crackers_snacks": {
    "classic_box": {
      "2026-05-06": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-05-13": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-05-20": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-03": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-10": {
        "price": null,
        "offerText": null,
        "confidence": null
      },
      "2026-06-17": {
        "price": 2.49,
        "offerText": "Ritz Crackers 5 to 13 oz",
        "confidence": "high"
      },
      "2026-06-24": {
        "price": 2.99,
        "offerText": "Nabisco Ritz Crackers",
        "confidence": "medium"
      },
      "2026-07-01": {
        "price": null,
        "offerText": null,
        "confidence": null
      }
    }
  }
};
