// AUTO-GENERATED by scripts/generate_vons_feed_matches.py — do not edit by hand.
// Source: data/processed/vons_baseline_candidates_v1.csv

export type VonsBaselineEntry = {
  baselinePrice: number;
  baselineSource: string;
  retailerProductId: string | null;
  upc: string | null;
  retailerProductName: string | null;
  size: string | null;
};

export const VONS_BASELINE_BY_CANONICAL: Record<string, VonsBaselineEntry> = {
  "strawberries": {
    "baselinePrice": 3.99,
    "baselineSource": "Vons search result CSV (rank 1)",
    "retailerProductId": "184070124",
    "upc": "0078035378403",
    "retailerProductName": "Strawberries Prepacked - 1 Lb",
    "size": "LB"
  },
  "avocados": {
    "baselinePrice": 1.5,
    "baselineSource": "Vons search result CSV (rank 1)",
    "retailerProductId": "184040105",
    "upc": "0048404010501",
    "retailerProductName": "Medium Hass Avocado",
    "size": "EACH"
  },
  "doritos_nacho_cheese": {
    "baselinePrice": 4.99,
    "baselineSource": "Vons search result CSV (rank 1)",
    "retailerProductId": "971373148",
    "upc": "0075752805414",
    "retailerProductName": "Takis Pickle Punch 9.9oz - 9.9 OZ",
    "size": "OUNCE"
  },
  "cheetos_crunchy": {
    "baselinePrice": 5.49,
    "baselineSource": "Vons search result CSV (rank 1)",
    "retailerProductId": "960156582",
    "upc": "0002840058986",
    "retailerProductName": "Cheetos Cheese Flavored Crunchy Snacks - 8.5 Oz",
    "size": "OUNCE"
  },
  "coke_zero": {
    "baselinePrice": 11.99,
    "baselineSource": "Vons search result CSV (rank 1)",
    "retailerProductId": "108010505",
    "upc": "0004900004255",
    "retailerProductName": "Coca-Cola Zero Sugar Soda Soft Drinks Fridge Cans Pack - 12-12 Fl. Oz.",
    "size": "FL.OZ"
  },
  "chobani_greek_yogurt": {
    "baselinePrice": 6.99,
    "baselineSource": "Vons search result CSV (rank 1)",
    "retailerProductId": "960055227",
    "upc": "0089470001014",
    "retailerProductName": "Chobani Non-Fat Vanilla Blended Greek Yogurt - 32 Oz",
    "size": "OUNCE"
  },
  "cheerios": {
    "baselinePrice": 6.49,
    "baselineSource": "Vons search result CSV (rank 1)",
    "retailerProductId": "960141527",
    "upc": "0004240093978",
    "retailerProductName": "Malt-O-Meal Cereal Cinnamon Toasters Super Size! - 33 Oz",
    "size": "OUNCE"
  },
  "tillamook_ice_cream": {
    "baselinePrice": 6.49,
    "baselineSource": "Vons search result CSV (rank 1)",
    "retailerProductId": "971322701",
    "upc": "0007684000454",
    "retailerProductName": "Ben & Jerry's Ice Cream Cookie Dough 10.1 Fz - 10.1 FZ",
    "size": "FL.OZ"
  },
  "mission_tortilla_chips": {
    "baselinePrice": 5.99,
    "baselineSource": "Vons search result CSV (rank 1)",
    "retailerProductId": "970031792",
    "upc": "0002840051779",
    "retailerProductName": "DORITOS Tortilla Chips Nacho Party Size - 14.5 OZ",
    "size": "OUNCE"
  },
  "nature_valley_bars": {
    "baselinePrice": 4.99,
    "baselineSource": "Vons search result CSV (rank 1)",
    "retailerProductId": "960265185",
    "upc": "0003800016778",
    "retailerProductName": "Kelloggs Special K Pastry Crisps Strawberry 100 Calorie Snacks 12 Count - 5.28 Oz",
    "size": "COUNT"
  },
  "fage_greek_yogurt": {
    "baselinePrice": 5.49,
    "baselineSource": "Vons search result CSV (rank 1)",
    "retailerProductId": "960050143",
    "upc": "0068954408301",
    "retailerProductName": "FAGE Total 0% Milkfat Plain Greek Yogurt - 32 Oz",
    "size": "OUNCE"
  },
  "frito_lay_multipack_chips": {
    "baselinePrice": 18.99,
    "baselineSource": "Vons search result CSV (rank 1)",
    "retailerProductId": "970125552",
    "upc": "0002840073738",
    "retailerProductName": "Frito Lay Variety Pack Flavor Mix - 42 Count",
    "size": "COUNT"
  },
  "haagen_dazs_ice_cream": {
    "baselinePrice": 6.49,
    "baselineSource": "Vons search result CSV (rank 1)",
    "retailerProductId": "970064358",
    "upc": "0007684000297",
    "retailerProductName": "Ben & Jerry's Colin Kaepernick's Change The Whirled Non-Dairy Frozen Dessert - 16 Oz",
    "size": "QUART"
  },
  "grapes": {
    "baselinePrice": 7.98,
    "baselineSource": "Vons search result CSV (rank 1)",
    "retailerProductId": "184100014",
    "upc": "0048410001401",
    "retailerProductName": "Green Seedless Grapes Prepacked Bag - 2 Lb",
    "size": "LB"
  },
  "eggs_18_count": {
    "baselinePrice": 1.99,
    "baselineSource": "Vons search result CSV (rank 1)",
    "retailerProductId": "960304348",
    "upc": "0002113003154",
    "retailerProductName": "Lucerne Farms Eggs Cage Free Large - 18 Count",
    "size": "DOZEN"
  },
  "oreos_sandwich_cookies": {
    "baselinePrice": 4.99,
    "baselineSource": "Vons search result CSV (rank 1)",
    "retailerProductId": "970485813",
    "upc": "0004400006023",
    "retailerProductName": "OREO Chocolate Sandwich Cookies Family Size - 18.12 Oz",
    "size": "OUNCE"
  },
  "protein_bars": {
    "baselinePrice": 14.99,
    "baselineSource": "Vons search result CSV (rank 1)",
    "retailerProductId": "960057545",
    "upc": "0072225216850",
    "retailerProductName": "CLIF BUILDERS Chocolatey Peanut Butter 20g Protein Bars - 6 Count",
    "size": "OUNCE"
  },
  "kettle_brand_chips": {
    "baselinePrice": 4.99,
    "baselineSource": "Vons search result CSV (rank 1)",
    "retailerProductId": "971360376",
    "upc": "0002840080061",
    "retailerProductName": "Miss Vickie's Kettle Cooked Potato Chips Jalapeno - 7.5 OZ",
    "size": "OUNCE"
  }
};
