// AUTO-GENERATED by scripts/generate_weekly_ad_prices.py — do not edit by hand.
// Source manifest: data/weekly_ads/flyer_manifest_vons.csv
// Source offers: scrolling-the-aisle/outputs/product_discovery_vons/split_offer_items.csv

export type WeeklyAdWeek = {
  weekStart: string;
  weekEnd: string;
  sourceFile: string;
  sourceLabel: string;
};

export type GeneratedWeeklyAdPrice = {
  price: number | null;
  offerText: string | null;
  confidence: "high" | "medium" | "low" | null;
};

export const VONS_WEEKLY_AD_WEEKS: WeeklyAdWeek[] = [
  {
    "weekStart": "2026-05-06",
    "weekEnd": "2026-05-12",
    "sourceFile": "vons 5-6 - 5-12.pdf",
    "sourceLabel": "Vons weekly ad 05/06\u201305/12"
  },
  {
    "weekStart": "2026-05-13",
    "weekEnd": "2026-05-19",
    "sourceFile": "vons 5-13 - 5-19.pdf",
    "sourceLabel": "Vons weekly ad 05/13\u201305/19"
  },
  {
    "weekStart": "2026-05-20",
    "weekEnd": "2026-05-26",
    "sourceFile": "vons 5-20 - 5-26.pdf",
    "sourceLabel": "Vons weekly ad 05/20\u201305/26"
  },
  {
    "weekStart": "2026-06-03",
    "weekEnd": "2026-06-09",
    "sourceFile": "vons 6-3 - 6-9.pdf",
    "sourceLabel": "Vons weekly ad 06/03\u201306/09"
  },
  {
    "weekStart": "2026-06-10",
    "weekEnd": "2026-06-16",
    "sourceFile": "vons 6-10 - 6-16.pdf",
    "sourceLabel": "Vons weekly ad 06/10\u201306/16"
  },
  {
    "weekStart": "2026-06-17",
    "weekEnd": "2026-06-23",
    "sourceFile": "vons 6-17 - 6-23.pdf",
    "sourceLabel": "Vons weekly ad 06/17\u201306/23"
  }
];

export const VONS_WEEKLY_AD_PRICES: Record<
  string,
  Record<string, GeneratedWeeklyAdPrice>
> = {
  "strawberries": {
    "2026-05-06": {
      "price": 1.99,
      "offerText": "Strawberries",
      "confidence": "high"
    },
    "2026-05-13": {
      "price": 2.57,
      "offerText": "Local Strawberries",
      "confidence": "medium"
    },
    "2026-05-20": {
      "price": 1.99,
      "offerText": "Strawberries 1 lb. package",
      "confidence": "medium"
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": 1.99,
      "offerText": "Strawberries 1 lb",
      "confidence": "medium"
    },
    "2026-06-17": {
      "price": 2.5,
      "offerText": "Fresh Strawberries",
      "confidence": "high"
    }
  },
  "avocados": {
    "2026-05-06": {
      "price": 1.5,
      "offerText": "Large Hass Avocados",
      "confidence": "high"
    },
    "2026-05-13": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-20": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": 1.67,
      "offerText": "Large Hass Avocados",
      "confidence": "high"
    }
  },
  "doritos_nacho_cheese": {
    "2026-05-06": {
      "price": 2.99,
      "offerText": "Doritos",
      "confidence": "high"
    },
    "2026-05-13": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-20": {
      "price": 3.67,
      "offerText": "Lay's, Kettle Cooked, Poppables, Doritos, Ruffles, Smartfood, Cheetos, Fritos",
      "confidence": "medium"
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": 3.99,
      "offerText": "Doritos, Ruffles",
      "confidence": "medium"
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "cheetos_crunchy": {
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-13": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-20": {
      "price": 3.67,
      "offerText": "Lay's, Kettle Cooked, Poppables, Doritos, Ruffles, Smartfood, Cheetos, Fritos",
      "confidence": "medium"
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": 2.49,
      "offerText": "Lay's, Kettle Cooked, Cheetos, Smartfood, Simply 4.75-10 oz. Tostitos Queso or Lay's Dip 15-15.75 oz. Selected varieties",
      "confidence": "medium"
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "coke_zero": {
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-13": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-20": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "chobani_greek_yogurt": {
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-13": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-20": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "cheerios": {
    "2026-05-06": {
      "price": 3.49,
      "offerText": "Cheerios Cereal",
      "confidence": "medium"
    },
    "2026-05-13": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-20": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": 1.99,
      "offerText": "Cheerios Cereal 8.9-12 oz",
      "confidence": "medium"
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "tillamook_ice_cream": {
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-13": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-20": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "mission_tortilla_chips": {
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-13": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-20": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "nature_valley_bars": {
    "2026-05-06": {
      "price": 2.99,
      "offerText": "Nature Valley Granola Bars",
      "confidence": "medium"
    },
    "2026-05-13": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-20": {
      "price": 1.49,
      "offerText": "Betty Crocker Fruit Snacks 4.5-8 oz, Nature Valley Granola Bars 5.3-8.94 oz, Fiber One Bars 5.34-7 oz",
      "confidence": "medium"
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": 2.99,
      "offerText": "General Mills Nature Valley Bars 5-6 ct",
      "confidence": "high"
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "fage_greek_yogurt": {
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-13": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-20": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "frito_lay_multipack_chips": {
    "2026-05-06": {
      "price": 0.56,
      "offerText": "Frito-Lay Multipack",
      "confidence": "medium"
    },
    "2026-05-13": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-20": {
      "price": 9.99,
      "offerText": "Frito-Lay Multipack 18 ct, Nabisco Multipack 12 ct",
      "confidence": "medium"
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "haagen_dazs_ice_cream": {
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-13": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-20": {
      "price": 4.5,
      "offerText": "H\u00e4agen-Dazs Ice Cream, Bars",
      "confidence": "medium"
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "grapes": {
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-13": {
      "price": 3.99,
      "offerText": "Green Seedless Grapes",
      "confidence": "high"
    },
    "2026-05-20": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": 1.97,
      "offerText": "Black Seedless Grapes",
      "confidence": "high"
    },
    "2026-06-10": {
      "price": 1.97,
      "offerText": "Green Seedless Grapes",
      "confidence": "high"
    },
    "2026-06-17": {
      "price": 2.5,
      "offerText": "Red Seedless Grapes",
      "confidence": "high"
    }
  },
  "eggs_18_count": {
    "2026-05-06": {
      "price": 0.99,
      "offerText": "Lucerne Cage Free Large Eggs",
      "confidence": "high"
    },
    "2026-05-13": {
      "price": 2.5,
      "offerText": "Lucerne Large Eggs 12 ct",
      "confidence": "high"
    },
    "2026-05-20": {
      "price": 2.99,
      "offerText": "Lucerne Large Eggs",
      "confidence": "high"
    },
    "2026-06-03": {
      "price": 1.99,
      "offerText": "Lucerne Large Eggs",
      "confidence": "high"
    },
    "2026-06-10": {
      "price": 2.99,
      "offerText": "Lucerne Large Eggs 18 ct",
      "confidence": "high"
    },
    "2026-06-17": {
      "price": 1.99,
      "offerText": "Lucerne Large Eggs 12 ct",
      "confidence": "high"
    }
  },
  "oreos_sandwich_cookies": {
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-13": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-20": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "protein_bars": {
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-13": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-20": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "kettle_brand_chips": {
    "2026-05-06": {
      "price": 2.99,
      "offerText": "Lay\u2019s Kettle Cooked",
      "confidence": "medium"
    },
    "2026-05-13": {
      "price": 1.88,
      "offerText": "Kettle Brand Potato Chips 6.5 to 8.5 oz",
      "confidence": "high"
    },
    "2026-05-20": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": 2.49,
      "offerText": "Cheez-Its, Club, Town House 9-13.8 oz. Kellogg\u2019s Bagged Crackers 5.75-7.5 oz. Keebler Sandwich Crackers 8 ct. Late July 7.5-10.1 oz. Kettle Brand or Cape Cod Chips 6.5-8 oz. Selected varieties",
      "confidence": "medium"
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  }
};
