// AUTO-GENERATED by scripts/generate_weekly_ad_prices.py — do not edit by hand.
// Source manifest: data/weekly_ads/flyer_manifest_safeway.csv
// Source offers: scrolling-the-aisle/outputs/product_discovery_safeway/split_offer_items.csv

export type WeeklyAdWeek = {
  weekStart: string;
  weekEnd: string;
  sourceFile: string;
  sourceLabel: string;
};

export type GeneratedWeeklyAdPrice = {
  price: number | null;
  offerText: string | null;
  confidence: "high" | "medium" | "low" | null;
};

export const WEEKLY_AD_WEEKS: WeeklyAdWeek[] = [
  {
    "weekStart": "2026-03-25",
    "weekEnd": "2026-03-31",
    "sourceFile": "safeway 3-25 - 3-31.pdf",
    "sourceLabel": "Safeway weekly ad 03/25\u201303/31"
  },
  {
    "weekStart": "2026-04-01",
    "weekEnd": "2026-04-07",
    "sourceFile": "safeway 4-1 - 4-7.pdf",
    "sourceLabel": "Safeway weekly ad 04/01\u201304/07"
  },
  {
    "weekStart": "2026-05-06",
    "weekEnd": "2026-05-12",
    "sourceFile": "safeway 5-6 - 5-12.pdf",
    "sourceLabel": "Safeway weekly ad 05/06\u201305/12"
  },
  {
    "weekStart": "2026-05-12",
    "weekEnd": "2026-05-19",
    "sourceFile": "safeway 5-12 - 5-19.pdf",
    "sourceLabel": "Safeway weekly ad 05/12\u201305/19"
  },
  {
    "weekStart": "2026-06-03",
    "weekEnd": "2026-06-09",
    "sourceFile": "safeway 6-3 - 6-9.pdf",
    "sourceLabel": "Safeway weekly ad 06/03\u201306/09"
  },
  {
    "weekStart": "2026-06-10",
    "weekEnd": "2026-06-16",
    "sourceFile": "safeway 6-10 - 6-16.pdf",
    "sourceLabel": "Safeway weekly ad 06/10\u201306/16"
  },
  {
    "weekStart": "2026-06-17",
    "weekEnd": "2026-06-23",
    "sourceFile": "safeway 6-17 - 6-23.pdf",
    "sourceLabel": "Safeway weekly ad 06/17\u201306/23"
  }
];

export const WEEKLY_AD_PRICES: Record<
  string,
  Record<string, GeneratedWeeklyAdPrice>
> = {
  "strawberries": {
    "2026-03-25": {
      "price": 2.5,
      "offerText": "Strawberries",
      "confidence": "high"
    },
    "2026-04-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-12": {
      "price": 4.99,
      "offerText": "Strawberries LARGE PACK",
      "confidence": "medium"
    },
    "2026-06-03": {
      "price": 4.99,
      "offerText": "Strawberries",
      "confidence": "medium"
    },
    "2026-06-10": {
      "price": 5.0,
      "offerText": "Strawberries LARGE PACK",
      "confidence": "medium"
    },
    "2026-06-17": {
      "price": 5.0,
      "offerText": "Strawberries",
      "confidence": "high"
    }
  },
  "avocados": {
    "2026-03-25": {
      "price": 1.67,
      "offerText": "Hass Avocado",
      "confidence": "high"
    },
    "2026-04-01": {
      "price": 0.97,
      "offerText": "Hass Avocado",
      "confidence": "high"
    },
    "2026-05-06": {
      "price": 1.67,
      "offerText": "Hass Avocado",
      "confidence": "high"
    },
    "2026-05-12": {
      "price": 1.25,
      "offerText": "Hass Avocado",
      "confidence": "high"
    },
    "2026-06-03": {
      "price": 1.67,
      "offerText": "Hass Avocado",
      "confidence": "high"
    },
    "2026-06-10": {
      "price": 0.99,
      "offerText": "Hass Avocado, Large Mango, Cucumber, Roma Tomato",
      "confidence": "medium"
    },
    "2026-06-17": {
      "price": 2.0,
      "offerText": "Hass Avocados",
      "confidence": "high"
    }
  },
  "doritos_nacho_cheese": {
    "2026-03-25": {
      "price": 1.99,
      "offerText": "Doritos Tortilla Chips",
      "confidence": "high"
    },
    "2026-04-01": {
      "price": 1.99,
      "offerText": "Lay\u2019s, Fritos, Doritos",
      "confidence": "medium"
    },
    "2026-05-06": {
      "price": null,
      "offerText": "Lay\u2019s, Doritos, Tostitos",
      "confidence": null
    },
    "2026-05-12": {
      "price": 4.99,
      "offerText": "Doritos",
      "confidence": "high"
    },
    "2026-06-03": {
      "price": 2.49,
      "offerText": "Ruffles, Doritos, SunChips",
      "confidence": "medium"
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": 2.49,
      "offerText": "Ruffles, Doritos, SunChips",
      "confidence": "medium"
    }
  },
  "cheetos_crunchy": {
    "2026-03-25": {
      "price": null,
      "offerText": "Cheetos",
      "confidence": null
    },
    "2026-04-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-12": {
      "price": 4.99,
      "offerText": "Cheetos, Tostitos, Fritos",
      "confidence": "medium"
    },
    "2026-06-03": {
      "price": 4.99,
      "offerText": "Cheetos, Rold Gold, Select Simply Cheetos 6.5-10 oz. Selected varieties.",
      "confidence": "medium"
    },
    "2026-06-10": {
      "price": null,
      "offerText": "Cheetos, Lay's, Simply",
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "coke_zero": {
    "2026-03-25": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-04-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-12": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "chobani_greek_yogurt": {
    "2026-03-25": {
      "price": 0.99,
      "offerText": "Chobani Greek, Less Sugar",
      "confidence": "medium"
    },
    "2026-04-01": {
      "price": 0.99,
      "offerText": "Chobani Greek Yogurt. Selected varieties.",
      "confidence": "medium"
    },
    "2026-05-06": {
      "price": 0.89,
      "offerText": "Chobani Greek, Less Sugar Yogurt 5.3-oz. 89\u00a2 MEMBER PRICE clip",
      "confidence": "medium"
    },
    "2026-05-12": {
      "price": 0.99,
      "offerText": "Chobani Greek Yogurt",
      "confidence": "medium"
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": 2.99,
      "offerText": "Chobani Greek Yogurt 4-5.3 oz. Selected varieties.",
      "confidence": "medium"
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "cheerios": {
    "2026-03-25": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-04-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-12": {
      "price": 1.99,
      "offerText": "General Mills Cheerios",
      "confidence": "high"
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "tillamook_ice_cream": {
    "2026-03-25": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-04-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-06": {
      "price": 3.99,
      "offerText": "Tillamook Ice Cream 48-oz. 3.99 MEMBER PRICE clip",
      "confidence": "medium"
    },
    "2026-05-12": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": 3.99,
      "offerText": "Tillamook Ice Cream",
      "confidence": "high"
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "mission_tortilla_chips": {
    "2026-03-25": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-04-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-06": {
      "price": 4.99,
      "offerText": "Mission Tortilla Chips",
      "confidence": "high"
    },
    "2026-05-12": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "nature_valley_bars": {
    "2026-03-25": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-04-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-12": {
      "price": 1.99,
      "offerText": "Nature Valley Bars",
      "confidence": "high"
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": 1.79,
      "offerText": "Nature Valley Bars 5-6 ct.",
      "confidence": "high"
    },
    "2026-06-17": {
      "price": 1.0,
      "offerText": "Betty Crocker Fruit Snacks 5 to 10 ct, Nature Valley Bars 5 to 12 ct",
      "confidence": "medium"
    }
  },
  "fage_greek_yogurt": {
    "2026-03-25": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-04-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-12": {
      "price": 5.0,
      "offerText": "Fage Greek Yogurt",
      "confidence": "high"
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": 5.99,
      "offerText": "Fage Yogurt",
      "confidence": "medium"
    },
    "2026-06-17": {
      "price": 0.5,
      "offerText": "Fage Greek Yogurt",
      "confidence": "high"
    }
  },
  "frito_lay_multipack_chips": {
    "2026-03-25": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-04-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-06": {
      "price": 11.99,
      "offerText": "Hint Water Variety Pack",
      "confidence": "medium"
    },
    "2026-05-12": {
      "price": 8.99,
      "offerText": "Frito-Lay Variety Pack",
      "confidence": "high"
    },
    "2026-06-03": {
      "price": 9.99,
      "offerText": "Frito-Lay Variety Pack 18 ct. Selected varieties.",
      "confidence": "high"
    },
    "2026-06-10": {
      "price": 14.0,
      "offerText": "Frito-Lay Flavor Mix 35 to 42-ct. Selected varieties.",
      "confidence": "medium"
    },
    "2026-06-17": {
      "price": 8.99,
      "offerText": "Frito-Lay Variety Pack",
      "confidence": "high"
    }
  },
  "haagen_dazs_ice_cream": {
    "2026-03-25": {
      "price": 1.25,
      "offerText": "Klondike Ice Cream Bars 6 ct, Jell-O Gelatin",
      "confidence": "medium"
    },
    "2026-04-01": {
      "price": 3.5,
      "offerText": "H\u00e4agen-Dazs Ice Cream Novelties",
      "confidence": "medium"
    },
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-12": {
      "price": 2.99,
      "offerText": "Dreyer's Ice Cream 1.5 qt., Haagen-Dazs Ice Cream 14 oz., Novelties 3-6 ct., Nestle Outshine Fruit Bars 6-12 ct.",
      "confidence": "medium"
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "grapes": {
    "2026-03-25": {
      "price": 2.49,
      "offerText": "Red Seedless Grapes",
      "confidence": "high"
    },
    "2026-04-01": {
      "price": 4.99,
      "offerText": "Pristine Green and Red Seedless Grapes",
      "confidence": "high"
    },
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-12": {
      "price": 2.49,
      "offerText": "Red Seedless Grapes",
      "confidence": "high"
    },
    "2026-06-03": {
      "price": 5.0,
      "offerText": "Red Seedless Grapes",
      "confidence": "high"
    },
    "2026-06-10": {
      "price": 1.99,
      "offerText": "Red Seedless Grapes",
      "confidence": "high"
    },
    "2026-06-17": {
      "price": 4.99,
      "offerText": "Red Seedless Grapes",
      "confidence": "high"
    }
  },
  "eggs_18_count": {
    "2026-03-25": {
      "price": 0.58,
      "offerText": "Eggland's Best Large Eggs",
      "confidence": "high"
    },
    "2026-04-01": {
      "price": 4.49,
      "offerText": "Hershey\u2019s Eggs, Mini Eggs",
      "confidence": "medium"
    },
    "2026-05-06": {
      "price": 7.49,
      "offerText": "Happy Egg Free Range Eggs",
      "confidence": "medium"
    },
    "2026-05-12": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": 6.99,
      "offerText": "Pete & Gerry\u2019s Free Range Organic Eggs 12 ct. Large, Grade A.",
      "confidence": "medium"
    },
    "2026-06-10": {
      "price": 2.99,
      "offerText": "Lucerne Cage Free Eggs Grade AA, 18-ct.",
      "confidence": "medium"
    },
    "2026-06-17": {
      "price": 7.49,
      "offerText": "Happy Egg Free Range Eggs 12 ct",
      "confidence": "medium"
    }
  },
  "oreos_sandwich_cookies": {
    "2026-03-25": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-04-01": {
      "price": null,
      "offerText": "OREO minis Snak-Saks Barnum's Animals Crackers",
      "confidence": null
    },
    "2026-05-06": {
      "price": 3.49,
      "offerText": "Nabisco Family Size Oreo Cookies or Chips Ahoy! Cookies 13.1 to 20-oz.",
      "confidence": "medium"
    },
    "2026-05-12": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": "Nabisco Family Size Oreo Cookies 13.1-20 oz.",
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "protein_bars": {
    "2026-03-25": {
      "price": 8.99,
      "offerText": "Built Protein Bars",
      "confidence": "high"
    },
    "2026-04-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-12": {
      "price": 11.99,
      "offerText": "CLIF BUILDERS Protein Bars 12 ct.",
      "confidence": "high"
    },
    "2026-06-03": {
      "price": 7.99,
      "offerText": "Perfect Bar Refrigerated Protein Bars 4-8 ct. Selected varieties.",
      "confidence": "high"
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "kettle_brand_chips": {
    "2026-03-25": {
      "price": 5.0,
      "offerText": "Kettle Chips",
      "confidence": "medium"
    },
    "2026-04-01": {
      "price": 5.0,
      "offerText": "Kettle Brand Potato Chips 6-8.5 oz",
      "confidence": "high"
    },
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-12": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": 1.99,
      "offerText": "Kettle Brand Potato Chips",
      "confidence": "high"
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-17": {
      "price": null,
      "offerText": "Kettle Cooked Chips",
      "confidence": null
    }
  }
};
