// AUTO-GENERATED by scripts/generate_weekly_ad_prices.py — do not edit by hand.
// Source manifest: data/weekly_ads/flyer_manifest_safeway.csv
// Source offers: scrolling-the-aisle/outputs/product_discovery_safeway/split_offer_items.csv

export type WeeklyAdWeek = {
  weekStart: string;
  weekEnd: string;
  sourceFile: string;
  sourceLabel: string;
};

export type GeneratedWeeklyAdPrice = {
  price: number | null;
  offerText: string | null;
  confidence: "high" | "medium" | "low" | null;
};

export const WEEKLY_AD_WEEKS: WeeklyAdWeek[] = [
  {
    "weekStart": "2026-03-25",
    "weekEnd": "2026-03-31",
    "sourceFile": "safeway 3-25 - 3-31.pdf",
    "sourceLabel": "Safeway weekly ad 03/25\u201303/31"
  },
  {
    "weekStart": "2026-04-01",
    "weekEnd": "2026-04-07",
    "sourceFile": "safeway 4-1 - 4-7.pdf",
    "sourceLabel": "Safeway weekly ad 04/01\u201304/07"
  },
  {
    "weekStart": "2026-05-06",
    "weekEnd": "2026-05-12",
    "sourceFile": "safeway 5-6 - 5-12.pdf",
    "sourceLabel": "Safeway weekly ad 05/06\u201305/12"
  },
  {
    "weekStart": "2026-05-12",
    "weekEnd": "2026-05-19",
    "sourceFile": "safeway 5-12 - 5-19.pdf",
    "sourceLabel": "Safeway weekly ad 05/12\u201305/19"
  },
  {
    "weekStart": "2026-06-03",
    "weekEnd": "2026-06-09",
    "sourceFile": "safeway 6-3 - 6-9.pdf",
    "sourceLabel": "Safeway weekly ad 06/03\u201306/09"
  },
  {
    "weekStart": "2026-06-10",
    "weekEnd": "2026-06-16",
    "sourceFile": "safeway 6-10 - 6-16.pdf",
    "sourceLabel": "Safeway weekly ad 06/10\u201306/16"
  }
];

export const WEEKLY_AD_PRICES: Record<
  string,
  Record<string, GeneratedWeeklyAdPrice>
> = {
  "strawberries": {
    "2026-03-25": {
      "price": 2.5,
      "offerText": "Strawberries",
      "confidence": "high"
    },
    "2026-04-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-12": {
      "price": 4.99,
      "offerText": "Strawberries LARGE PACK",
      "confidence": "medium"
    },
    "2026-06-03": {
      "price": 4.99,
      "offerText": "Strawberries",
      "confidence": "medium"
    },
    "2026-06-10": {
      "price": 5.0,
      "offerText": "Strawberries LARGE PACK",
      "confidence": "medium"
    }
  },
  "avocados": {
    "2026-03-25": {
      "price": 1.67,
      "offerText": "Hass Avocado",
      "confidence": "high"
    },
    "2026-04-01": {
      "price": 0.97,
      "offerText": "Hass Avocado",
      "confidence": "high"
    },
    "2026-05-06": {
      "price": 1.67,
      "offerText": "Hass Avocado",
      "confidence": "high"
    },
    "2026-05-12": {
      "price": 1.25,
      "offerText": "Hass Avocado",
      "confidence": "high"
    },
    "2026-06-03": {
      "price": 1.67,
      "offerText": "Hass Avocado",
      "confidence": "high"
    },
    "2026-06-10": {
      "price": 0.99,
      "offerText": "Hass Avocado, Large Mango, Cucumber, Roma Tomato",
      "confidence": "medium"
    }
  },
  "doritos_nacho_cheese": {
    "2026-03-25": {
      "price": 1.99,
      "offerText": "Doritos Tortilla Chips",
      "confidence": "high"
    },
    "2026-04-01": {
      "price": 1.99,
      "offerText": "Lay\u2019s, Fritos, Doritos",
      "confidence": "medium"
    },
    "2026-05-06": {
      "price": null,
      "offerText": "Lay\u2019s, Doritos, Tostitos",
      "confidence": null
    },
    "2026-05-12": {
      "price": 4.99,
      "offerText": "Doritos",
      "confidence": "high"
    },
    "2026-06-03": {
      "price": 2.49,
      "offerText": "Ruffles, Doritos, SunChips",
      "confidence": "medium"
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "cheetos_crunchy": {
    "2026-03-25": {
      "price": null,
      "offerText": "Cheetos",
      "confidence": null
    },
    "2026-04-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-12": {
      "price": 4.99,
      "offerText": "Cheetos, Tostitos, Fritos",
      "confidence": "medium"
    },
    "2026-06-03": {
      "price": 4.99,
      "offerText": "Cheetos, Rold Gold, Select Simply Cheetos 6.5-10 oz. Selected varieties.",
      "confidence": "medium"
    },
    "2026-06-10": {
      "price": null,
      "offerText": "Cheetos, Lay's, Simply",
      "confidence": null
    }
  },
  "coke_zero": {
    "2026-03-25": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-04-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-12": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "chobani_greek_yogurt": {
    "2026-03-25": {
      "price": 0.99,
      "offerText": "Chobani Greek, Less Sugar",
      "confidence": "medium"
    },
    "2026-04-01": {
      "price": 0.99,
      "offerText": "Chobani Greek Yogurt. Selected varieties.",
      "confidence": "medium"
    },
    "2026-05-06": {
      "price": 0.89,
      "offerText": "Chobani Greek, Less Sugar Yogurt 5.3-oz. 89\u00a2 MEMBER PRICE clip",
      "confidence": "medium"
    },
    "2026-05-12": {
      "price": 0.99,
      "offerText": "Chobani Greek Yogurt",
      "confidence": "medium"
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": 2.99,
      "offerText": "Chobani Greek Yogurt 4-5.3 oz. Selected varieties.",
      "confidence": "medium"
    }
  },
  "cheerios": {
    "2026-03-25": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-04-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-12": {
      "price": 1.99,
      "offerText": "General Mills Cheerios",
      "confidence": "high"
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "tillamook_ice_cream": {
    "2026-03-25": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-04-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-06": {
      "price": 3.99,
      "offerText": "Tillamook Ice Cream 48-oz. 3.99 MEMBER PRICE clip",
      "confidence": "medium"
    },
    "2026-05-12": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": 3.99,
      "offerText": "Tillamook Ice Cream",
      "confidence": "high"
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "mission_tortilla_chips": {
    "2026-03-25": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-04-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-06": {
      "price": 4.99,
      "offerText": "Mission Tortilla Chips",
      "confidence": "high"
    },
    "2026-05-12": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": null,
      "offerText": null,
      "confidence": null
    }
  },
  "nature_valley_bars": {
    "2026-03-25": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-04-01": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-06": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-05-12": {
      "price": 1.99,
      "offerText": "Nature Valley Bars",
      "confidence": "high"
    },
    "2026-06-03": {
      "price": null,
      "offerText": null,
      "confidence": null
    },
    "2026-06-10": {
      "price": 1.79,
      "offerText": "Nature Valley Bars 5-6 ct.",
      "confidence": "high"
    }
  }
};
